// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/bucket-list" | "/chat" | "/explore" | "/globe" | "/journal" | "/login" | "/map" | "/onboarding" | "/profile" | "/settings" | "/signup" | "/t/[shareSlug]" | "/trips" | "/trips/[tripId]" | "/trips/new"
type AppRouteHandlerRoutes = "/api/chat" | "/api/journal" | "/api/places/search" | "/api/profile" | "/api/trips" | "/api/trips/[id]" | "/api/trips/[id]/days/[dayIndex]/optimize" | "/api/trips/[id]/feedback" | "/api/trips/[id]/hydrate-map" | "/api/trips/[id]/items/bulk" | "/api/trips/share/[slug]" | "/api/trips/share/[slug]/feedback" | "/api/user-places" | "/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/chat": {}
  "/api/journal": {}
  "/api/places/search": {}
  "/api/profile": {}
  "/api/trips": {}
  "/api/trips/[id]": { "id": string; }
  "/api/trips/[id]/days/[dayIndex]/optimize": { "id": string; "dayIndex": string; }
  "/api/trips/[id]/feedback": { "id": string; }
  "/api/trips/[id]/hydrate-map": { "id": string; }
  "/api/trips/[id]/items/bulk": { "id": string; }
  "/api/trips/share/[slug]": { "slug": string; }
  "/api/trips/share/[slug]/feedback": { "slug": string; }
  "/api/user-places": {}
  "/bucket-list": {}
  "/callback": {}
  "/chat": {}
  "/explore": {}
  "/globe": {}
  "/journal": {}
  "/login": {}
  "/map": {}
  "/onboarding": {}
  "/profile": {}
  "/settings": {}
  "/signup": {}
  "/t/[shareSlug]": { "shareSlug": string; }
  "/trips": {}
  "/trips/[tripId]": { "tripId": string; }
  "/trips/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
