// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../app/(app)/bucket-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bucket-list">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/bucket-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/globe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/globe">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/globe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/trips/[tripId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/[tripId]">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/trips/[tripId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/trips/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips/new">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/trips/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(app)/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trips">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../../app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/t/[shareSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[shareSlug]">> = Specific
  const handler = {} as typeof import("../../../../app/t/[shareSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(auth)/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/callback">> = Specific
  const handler = {} as typeof import("../../../../app/(auth)/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/journal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal">> = Specific
  const handler = {} as typeof import("../../../../app/api/journal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/places/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places/search">> = Specific
  const handler = {} as typeof import("../../../../app/api/places/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/[id]/days/[dayIndex]/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/days/[dayIndex]/optimize">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/[id]/days/[dayIndex]/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/[id]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/feedback">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/[id]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/[id]/hydrate-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/hydrate-map">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/[id]/hydrate-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/[id]/items/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]/items/bulk">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/[id]/items/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[id]">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/share/[slug]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/share/[slug]/feedback">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/share/[slug]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/trips/share/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/share/[slug]">> = Specific
  const handler = {} as typeof import("../../../../app/api/trips/share/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/user-places/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user-places">> = Specific
  const handler = {} as typeof import("../../../../app/api/user-places/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
