export type RegionalPlaceOverride = {
  pattern: RegExp
  name: string
  country: string
  country_code: string
  latitude: number
  longitude: number
  manualId: string
}

export const REGIONAL_PLACE_OVERRIDES: RegionalPlaceOverride[] = [
  { pattern: /hagia sophia/i, name: 'Hagia Sophia Grand Mosque', country: 'Turkey', country_code: 'TR', latitude: 41.00858, longitude: 28.98017, manualId: 'manual:istanbul:hagia-sophia' },
  { pattern: /\bmatbah\b/i, name: 'Matbah Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.00769, longitude: 28.97973, manualId: 'manual:istanbul:matbah' },
  { pattern: /basilica cistern/i, name: 'Basilica Cistern', country: 'Turkey', country_code: 'TR', latitude: 41.00838, longitude: 28.97788, manualId: 'manual:istanbul:basilica-cistern' },
  { pattern: /grand bazaar/i, name: 'Grand Bazaar', country: 'Turkey', country_code: 'TR', latitude: 41.01068, longitude: 28.96807, manualId: 'manual:istanbul:grand-bazaar' },
  { pattern: /seven hills/i, name: 'Seven Hills Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.00597, longitude: 28.98072, manualId: 'manual:istanbul:seven-hills' },
  { pattern: /mısır çarşısı|misir carsisi|spice bazaar/i, name: 'Mısır Çarşısı', country: 'Turkey', country_code: 'TR', latitude: 41.01646, longitude: 28.97055, manualId: 'manual:istanbul:spice-bazaar' },
  { pattern: /pandeli/i, name: 'Pandeli Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.01644, longitude: 28.97046, manualId: 'manual:istanbul:pandeli' },
  { pattern: /eminönü ferry|eminonu ferry|şehir hatları eminönü|sehir hatlari eminonu/i, name: 'Eminönü Ferry Terminal', country: 'Turkey', country_code: 'TR', latitude: 41.01728, longitude: 28.97507, manualId: 'manual:istanbul:eminonu-ferry' },
  { pattern: /kadıköy çarşı|kadikoy carsisi|kadıköy market|kadikoy market/i, name: 'Kadıköy Çarşı', country: 'Turkey', country_code: 'TR', latitude: 40.99057, longitude: 29.02647, manualId: 'manual:istanbul:kadikoy-carsi' },
  { pattern: /hamdi/i, name: 'Hamdi Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.01641, longitude: 28.97097, manualId: 'manual:istanbul:hamdi' },
  { pattern: /topkapı palace|topkapi palace/i, name: 'Topkapı Palace Museum', country: 'Turkey', country_code: 'TR', latitude: 41.01152, longitude: 28.98338, manualId: 'manual:istanbul:topkapi-palace' },
  { pattern: /karaköy lokantası|karakoy lokantasi/i, name: 'Karaköy Lokantası', country: 'Turkey', country_code: 'TR', latitude: 41.02432, longitude: 28.97705, manualId: 'manual:istanbul:karakoy-lokantasi' },
  { pattern: /galata tower/i, name: 'Galata Tower', country: 'Turkey', country_code: 'TR', latitude: 41.02557, longitude: 28.97413, manualId: 'manual:istanbul:galata-tower' },
  { pattern: /istanbul modern|i̇stanbul modern/i, name: 'Istanbul Modern', country: 'Turkey', country_code: 'TR', latitude: 41.02589, longitude: 28.98237, manualId: 'manual:istanbul:modern' },
  { pattern: /\bmikla\b/i, name: 'Mikla', country: 'Turkey', country_code: 'TR', latitude: 41.02814, longitude: 28.97493, manualId: 'manual:istanbul:mikla' },
  { pattern: /balat antik/i, name: 'Balat Antik Cafe', country: 'Turkey', country_code: 'TR', latitude: 41.02924, longitude: 28.94993, manualId: 'manual:istanbul:balat-antik' },
  { pattern: /fener rum|orthodox patriarchate/i, name: 'Fener Greek Orthodox Patriarchate', country: 'Turkey', country_code: 'TR', latitude: 41.02978, longitude: 28.95151, manualId: 'manual:istanbul:fener-patriarchate' },
  { pattern: /bulgarian st\.?\s*stephen|st\.?\s*stephen church|sveti stefan/i, name: 'Bulgarian St. Stephen Church', country: 'Turkey', country_code: 'TR', latitude: 41.0296, longitude: 28.94952, manualId: 'manual:istanbul:bulgarian-st-stephen' },
  { pattern: /chora church|kariye mosque/i, name: 'Chora Church', country: 'Turkey', country_code: 'TR', latitude: 41.03193, longitude: 28.93938, manualId: 'manual:istanbul:chora-church' },
  { pattern: /meze by lemon tree/i, name: 'Meze By Lemon Tree', country: 'Turkey', country_code: 'TR', latitude: 41.03141, longitude: 28.97301, manualId: 'manual:istanbul:meze-lemon-tree' },

  { pattern: /gyeongbokgung/i, name: 'Gyeongbokgung Palace', country: 'South Korea', country_code: 'KR', latitude: 37.57962, longitude: 126.97704, manualId: 'manual:seoul:gyeongbokgung' },
  { pattern: /tosokchon/i, name: 'Tosokchon Samgyetang', country: 'South Korea', country_code: 'KR', latitude: 37.57741, longitude: 126.97191, manualId: 'manual:seoul:tosokchon' },
  { pattern: /bukchon hanok/i, name: 'Bukchon Hanok Village', country: 'South Korea', country_code: 'KR', latitude: 37.5826, longitude: 126.984, manualId: 'manual:seoul:bukchon-hanok' },
  { pattern: /cheongsudang/i, name: 'Cheongsudang', country: 'South Korea', country_code: 'KR', latitude: 37.57438, longitude: 126.98966, manualId: 'manual:seoul:cheongsudang' },
  { pattern: /changhwadang/i, name: 'Changhwadang Ikseon', country: 'South Korea', country_code: 'KR', latitude: 37.57403, longitude: 126.98992, manualId: 'manual:seoul:changhwadang-ikseon' },
  { pattern: /myeong-?dong cathedral/i, name: 'Myeongdong Cathedral', country: 'South Korea', country_code: 'KR', latitude: 37.56337, longitude: 126.98734, manualId: 'manual:seoul:myeongdong-cathedral' },
  { pattern: /myeongdong kyoja/i, name: 'Myeongdong Kyoja Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56255, longitude: 126.98506, manualId: 'manual:seoul:myeongdong-kyoja' },
  { pattern: /lotte department store.*main/i, name: 'Lotte Department Store Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56482, longitude: 126.98164, manualId: 'manual:seoul:lotte-main-store' },
  { pattern: /wangbijip/i, name: 'Wangbijip Myeongdong Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56298, longitude: 126.9858, manualId: 'manual:seoul:wangbijip-myeongdong' },
  { pattern: /n seoul tower|namsan tower/i, name: 'N Seoul Tower', country: 'South Korea', country_code: 'KR', latitude: 37.55117, longitude: 126.98823, manualId: 'manual:seoul:n-seoul-tower' },
  { pattern: /starfield coex|coex mall/i, name: 'Starfield COEX Mall', country: 'South Korea', country_code: 'KR', latitude: 37.51168, longitude: 127.05915, manualId: 'manual:seoul:starfield-coex' },
  { pattern: /woo lae oak.*coex|wooraeok.*coex/i, name: 'Woo Lae Oak COEX', country: 'South Korea', country_code: 'KR', latitude: 37.51282, longitude: 127.05912, manualId: 'manual:seoul:woo-lae-oak-coex' },
  { pattern: /bongeunsa/i, name: 'Bongeunsa Temple', country: 'South Korea', country_code: 'KR', latitude: 37.515, longitude: 127.0574, manualId: 'manual:seoul:bongeunsa' },
  { pattern: /spa lei/i, name: 'Spa Lei', country: 'South Korea', country_code: 'KR', latitude: 37.51654, longitude: 127.01935, manualId: 'manual:seoul:spa-lei' },
  { pattern: /yang good/i, name: 'Yang Good Gangnam Main Branch', country: 'South Korea', country_code: 'KR', latitude: 37.5139, longitude: 127.0287, manualId: 'manual:seoul:yang-good-gangnam' },
  { pattern: /gyeongui line forest/i, name: 'Gyeongui Line Forest Park', country: 'South Korea', country_code: 'KR', latitude: 37.5596, longitude: 126.9237, manualId: 'manual:seoul:gyeongui-line-forest' },
  { pattern: /cafe layered.*yeonnam|layered yeonnam/i, name: 'Cafe Layered Yeonnam', country: 'South Korea', country_code: 'KR', latitude: 37.5623, longitude: 126.9236, manualId: 'manual:seoul:cafe-layered-yeonnam' },
  { pattern: /hongdae shopping/i, name: 'Hongdae Shopping Street', country: 'South Korea', country_code: 'KR', latitude: 37.553, longitude: 126.9226, manualId: 'manual:seoul:hongdae-shopping-street' },
  { pattern: /myth jokbal/i, name: 'Myth Jokbal Hongdae', country: 'South Korea', country_code: 'KR', latitude: 37.5508, longitude: 126.9219, manualId: 'manual:seoul:myth-jokbal-hongdae' },
  { pattern: /sangsangmadang/i, name: 'KT&G Sangsangmadang Hongdae', country: 'South Korea', country_code: 'KR', latitude: 37.5507, longitude: 126.921, manualId: 'manual:seoul:sangsangmadang-hongdae' },
  { pattern: /^seoul forest(?:,|$)|seoul forest park/i, name: 'Seoul Forest', country: 'South Korea', country_code: 'KR', latitude: 37.54439, longitude: 127.03744, manualId: 'manual:seoul:seoul-forest' },
  { pattern: /grandmother'?s recipe/i, name: "Grandmother's Recipe", country: 'South Korea', country_code: 'KR', latitude: 37.5471, longitude: 127.0429, manualId: 'manual:seoul:grandmothers-recipe' },
  { pattern: /musinsa standard.*seongsu/i, name: 'Musinsa Standard Seongsu', country: 'South Korea', country_code: 'KR', latitude: 37.5446, longitude: 127.054, manualId: 'manual:seoul:musinsa-standard-seongsu' },
  { pattern: /center coffee.*seoul forest/i, name: 'Center Coffee Seoul Forest', country: 'South Korea', country_code: 'KR', latitude: 37.5467, longitude: 127.0436, manualId: 'manual:seoul:center-coffee-seoul-forest' },
  { pattern: /banpo hangang/i, name: 'Banpo Hangang Park', country: 'South Korea', country_code: 'KR', latitude: 37.5126, longitude: 126.9961, manualId: 'manual:seoul:banpo-hangang-park' },

  { pattern: /wat pho/i, name: 'Wat Pho', country: 'Thailand', country_code: 'TH', latitude: 13.74651, longitude: 100.49276, manualId: 'manual:bangkok:wat-pho' },
  { pattern: /the sixth|6th/i, name: 'The Sixth 6th', country: 'Thailand', country_code: 'TH', latitude: 13.74496, longitude: 100.49264, manualId: 'manual:bangkok:the-sixth' },
  { pattern: /grand palace/i, name: 'Grand Palace', country: 'Thailand', country_code: 'TH', latitude: 13.75003, longitude: 100.49135, manualId: 'manual:bangkok:grand-palace' },
  { pattern: /wat arun/i, name: 'Wat Arun', country: 'Thailand', country_code: 'TH', latitude: 13.74372, longitude: 100.48894, manualId: 'manual:bangkok:wat-arun' },
  { pattern: /supanniga/i, name: 'Supanniga Eating Room Tha Tien', country: 'Thailand', country_code: 'TH', latitude: 13.74434, longitude: 100.49284, manualId: 'manual:bangkok:supanniga-tha-tien' },
  { pattern: /jim thompson/i, name: 'Jim Thompson House Museum', country: 'Thailand', country_code: 'TH', latitude: 13.74912, longitude: 100.52839, manualId: 'manual:bangkok:jim-thompson-house' },
  { pattern: /baan khun mae|ban khun mae/i, name: 'Baan Khun Mae', country: 'Thailand', country_code: 'TH', latitude: 13.74652, longitude: 100.53232, manualId: 'manual:bangkok:baan-khun-mae' },
  { pattern: /bangkok art and culture|bacc/i, name: 'Bangkok Art and Culture Centre', country: 'Thailand', country_code: 'TH', latitude: 13.74666, longitude: 100.53005, manualId: 'manual:bangkok:bacc' },
  { pattern: /jodd fairs/i, name: 'Jodd Fairs Night Market', country: 'Thailand', country_code: 'TH', latitude: 13.75881, longitude: 100.56551, manualId: 'manual:bangkok:jodd-fairs' },
  { pattern: /chatuchak/i, name: 'Chatuchak Weekend Market', country: 'Thailand', country_code: 'TH', latitude: 13.79982, longitude: 100.55053, manualId: 'manual:bangkok:chatuchak' },
  { pattern: /or tor kor/i, name: 'Or Tor Kor Market', country: 'Thailand', country_code: 'TH', latitude: 13.79788, longitude: 100.54879, manualId: 'manual:bangkok:or-tor-kor' },
  { pattern: /lumphini|lumpini/i, name: 'Lumphini Park', country: 'Thailand', country_code: 'TH', latitude: 13.73072, longitude: 100.54178, manualId: 'manual:bangkok:lumphini-park' },
  { pattern: /tep bar/i, name: 'Tep Bar', country: 'Thailand', country_code: 'TH', latitude: 13.73841, longitude: 100.51308, manualId: 'manual:bangkok:tep-bar' },
  { pattern: /wat traimit/i, name: 'Wat Traimit', country: 'Thailand', country_code: 'TH', latitude: 13.7378, longitude: 100.5137, manualId: 'manual:bangkok:wat-traimit' },
  { pattern: /nai ek/i, name: 'Nai Ek Roll Noodle', country: 'Thailand', country_code: 'TH', latitude: 13.74048, longitude: 100.51042, manualId: 'manual:bangkok:nai-ek' },
  { pattern: /yaowarat/i, name: 'Yaowarat Road', country: 'Thailand', country_code: 'TH', latitude: 13.74004, longitude: 100.51004, manualId: 'manual:bangkok:yaowarat-road' },
  { pattern: /pak khlong talat|flower market/i, name: 'Pak Khlong Talat', country: 'Thailand', country_code: 'TH', latitude: 13.7419, longitude: 100.49643, manualId: 'manual:bangkok:pak-khlong-talat' },
  { pattern: /ruen mallika/i, name: 'Ruen Mallika Royal Thai Cuisine', country: 'Thailand', country_code: 'TH', latitude: 13.7229, longitude: 100.53372, manualId: 'manual:bangkok:ruen-mallika' },

  { pattern: /le jardin secret/i, name: 'Le Jardin Secret', country: 'Morocco', country_code: 'MA', latitude: 31.63014, longitude: -7.9892, manualId: 'manual:marrakech:le-jardin-secret' },
  { pattern: /^nomad|nomad,/i, name: 'Nomad', country: 'Morocco', country_code: 'MA', latitude: 31.62831, longitude: -7.98757, manualId: 'manual:marrakech:nomad' },
  { pattern: /maison de la photographie/i, name: 'Maison de la Photographie', country: 'Morocco', country_code: 'MA', latitude: 31.63171, longitude: -7.98538, manualId: 'manual:marrakech:maison-photographie' },
  { pattern: /dar cherifa/i, name: 'Dar Cherifa', country: 'Morocco', country_code: 'MA', latitude: 31.63055, longitude: -7.9893, manualId: 'manual:marrakech:dar-cherifa' },
  { pattern: /souk semmarine/i, name: 'Souk Semmarine', country: 'Morocco', country_code: 'MA', latitude: 31.62776, longitude: -7.98813, manualId: 'manual:marrakech:souk-semmarine' },
  { pattern: /jardin majorelle/i, name: 'Jardin Majorelle', country: 'Morocco', country_code: 'MA', latitude: 31.64172, longitude: -8.00327, manualId: 'manual:marrakech:jardin-majorelle' },
  { pattern: /yves saint laurent|ysl/i, name: 'Musée Yves Saint Laurent Marrakech', country: 'Morocco', country_code: 'MA', latitude: 31.6429, longitude: -8.00331, manualId: 'manual:marrakech:ysl-museum' },
  { pattern: /plus61/i, name: 'Plus61', country: 'Morocco', country_code: 'MA', latitude: 31.62901, longitude: -8.01575, manualId: 'manual:marrakech:plus61' },
  { pattern: /cyber park|arsat moulay/i, name: 'Cyber Park Arsat Moulay Abdeslam', country: 'Morocco', country_code: 'MA', latitude: 31.62679, longitude: -8.00074, manualId: 'manual:marrakech:cyber-park' },
  { pattern: /^le jardin$|le jardin,/i, name: 'Le Jardin', country: 'Morocco', country_code: 'MA', latitude: 31.6306, longitude: -7.98695, manualId: 'manual:marrakech:le-jardin' },
  { pattern: /bahia palace/i, name: 'Bahia Palace', country: 'Morocco', country_code: 'MA', latitude: 31.62181, longitude: -7.98204, manualId: 'manual:marrakech:bahia-palace' },
  { pattern: /el badi|badi palace/i, name: 'El Badi Palace', country: 'Morocco', country_code: 'MA', latitude: 31.61872, longitude: -7.98672, manualId: 'manual:marrakech:el-badi-palace' },
  { pattern: /dar si said/i, name: 'Dar Si Said Museum', country: 'Morocco', country_code: 'MA', latitude: 31.62332, longitude: -7.98415, manualId: 'manual:marrakech:dar-si-said' },
  { pattern: /la famille/i, name: 'La Famille', country: 'Morocco', country_code: 'MA', latitude: 31.62347, longitude: -7.98578, manualId: 'manual:marrakech:la-famille' },
  { pattern: /kabana/i, name: 'Kabana', country: 'Morocco', country_code: 'MA', latitude: 31.6271, longitude: -7.99046, manualId: 'manual:marrakech:kabana' },

  { pattern: /table mountain aerial cableway/i, name: 'Table Mountain Aerial Cableway', country: 'South Africa', country_code: 'ZA', latitude: -33.9486, longitude: 18.4035, manualId: 'manual:cape-town:table-mountain-cableway' },
  { pattern: /bo-?kaap museum/i, name: 'Bo-Kaap Museum', country: 'South Africa', country_code: 'ZA', latitude: -33.9219, longitude: 18.4156, manualId: 'manual:cape-town:bo-kaap-museum' },
  { pattern: /kloof street house/i, name: 'Kloof Street House', country: 'South Africa', country_code: 'ZA', latitude: -33.9295, longitude: 18.4105, manualId: 'manual:cape-town:kloof-street-house' },
  { pattern: /signal hill/i, name: 'Signal Hill', country: 'South Africa', country_code: 'ZA', latitude: -33.9177, longitude: 18.4031, manualId: 'manual:cape-town:signal-hill' },
  { pattern: /athletic club.*social/i, name: 'The Athletic Club & Social', country: 'South Africa', country_code: 'ZA', latitude: -33.923, longitude: 18.4173, manualId: 'manual:cape-town:athletic-club-social' },
  { pattern: /lion'?s head/i, name: "Lion's Head Trailhead", country: 'South Africa', country_code: 'ZA', latitude: -33.9368, longitude: 18.3926, manualId: 'manual:cape-town:lions-head-trailhead' },
  { pattern: /jarryds/i, name: 'JARRYDS Brunch & Bistro', country: 'South Africa', country_code: 'ZA', latitude: -33.9184, longitude: 18.3852, manualId: 'manual:cape-town:jarryds' },
  { pattern: /clifton 4th|fourth beach/i, name: 'Clifton 4th Beach', country: 'South Africa', country_code: 'ZA', latitude: -33.9408, longitude: 18.3757, manualId: 'manual:cape-town:clifton-4th-beach' },
  { pattern: /camps bay beach/i, name: 'Camps Bay Beach', country: 'South Africa', country_code: 'ZA', latitude: -33.9513, longitude: 18.384, manualId: 'manual:cape-town:camps-bay-beach' },
  { pattern: /codfather/i, name: 'Codfather Seafood & Sushi', country: 'South Africa', country_code: 'ZA', latitude: -33.9548, longitude: 18.3814, manualId: 'manual:cape-town:codfather' },
  { pattern: /groot constantia/i, name: 'Groot Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0314, longitude: 18.4198, manualId: 'manual:cape-town:groot-constantia' },
  { pattern: /chefs warehouse.*beau constantia/i, name: 'Chefs Warehouse at Beau Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0206, longitude: 18.4027, manualId: 'manual:cape-town:chefs-warehouse-beau-constantia' },
  { pattern: /^beau constantia(?:,|$)/i, name: 'Beau Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0204, longitude: 18.4031, manualId: 'manual:cape-town:beau-constantia' },
  { pattern: /constantia glen/i, name: 'Constantia Glen', country: 'South Africa', country_code: 'ZA', latitude: -34.0089, longitude: 18.4053, manualId: 'manual:cape-town:constantia-glen' },
  { pattern: /buitenverwachting/i, name: 'Buitenverwachting', country: 'South Africa', country_code: 'ZA', latitude: -34.0316, longitude: 18.4318, manualId: 'manual:cape-town:buitenverwachting' },
  { pattern: /franschhoek wine tram/i, name: 'Franschhoek Wine Tram', country: 'South Africa', country_code: 'ZA', latitude: -33.9107, longitude: 19.1191, manualId: 'manual:franschhoek:wine-tram' },
  { pattern: /chamonix wine farm/i, name: 'Chamonix Wine Farm', country: 'South Africa', country_code: 'ZA', latitude: -33.8942, longitude: 19.1133, manualId: 'manual:franschhoek:chamonix-wine-farm' },
  { pattern: /la petite colombe/i, name: 'La Petite Colombe', country: 'South Africa', country_code: 'ZA', latitude: -33.8948, longitude: 19.1091, manualId: 'manual:franschhoek:la-petite-colombe' },
  { pattern: /^gold restaurant|gold street/i, name: 'GOLD Restaurant', country: 'South Africa', country_code: 'ZA', latitude: -33.9141, longitude: 18.4175, manualId: 'manual:cape-town:gold-restaurant' },
  { pattern: /seaforth restaurant/i, name: 'Seaforth Restaurant', country: 'South Africa', country_code: 'ZA', latitude: -34.1955, longitude: 18.4507, manualId: 'manual:simonstown:seaforth-restaurant' },
  { pattern: /boulders beach|penguin colony/i, name: 'Boulders Beach Penguin Colony', country: 'South Africa', country_code: 'ZA', latitude: -34.197, longitude: 18.4519, manualId: 'manual:simonstown:boulders-beach' },
  { pattern: /cape of good hope/i, name: 'Cape of Good Hope', country: 'South Africa', country_code: 'ZA', latitude: -34.3568, longitude: 18.474, manualId: 'manual:cape-point:cape-of-good-hope' },
  { pattern: /cape point/i, name: 'Cape Point', country: 'South Africa', country_code: 'ZA', latitude: -34.356, longitude: 18.4964, manualId: 'manual:cape-point:cape-point' },
  { pattern: /harbour house.*kalk bay/i, name: 'Harbour House Kalk Bay', country: 'South Africa', country_code: 'ZA', latitude: -34.1274, longitude: 18.449, manualId: 'manual:kalk-bay:harbour-house' },
  { pattern: /kirstenbosch/i, name: 'Kirstenbosch National Botanical Garden', country: 'South Africa', country_code: 'ZA', latitude: -33.9881, longitude: 18.4326, manualId: 'manual:cape-town:kirstenbosch' },
  { pattern: /oranjezicht city farm/i, name: 'Oranjezicht City Farm Market', country: 'South Africa', country_code: 'ZA', latitude: -33.9046, longitude: 18.4148, manualId: 'manual:cape-town:oranjezicht-market' },
  { pattern: /v\s*&\s*a waterfront|v&a waterfront|cape town waterfront/i, name: 'V&A Waterfront', country: 'South Africa', country_code: 'ZA', latitude: -33.9068, longitude: 18.4206, manualId: 'manual:cape-town:va-waterfront' },
  { pattern: /zeitz mocaa/i, name: 'Zeitz MOCAA', country: 'South Africa', country_code: 'ZA', latitude: -33.9085, longitude: 18.4228, manualId: 'manual:cape-town:zeitz-mocaa' },
  { pattern: /old biscuit mill/i, name: 'The Old Biscuit Mill', country: 'South Africa', country_code: 'ZA', latitude: -33.9273, longitude: 18.4575, manualId: 'manual:cape-town:old-biscuit-mill' },
  { pattern: /lawns.*roundhouse/i, name: 'The Lawns at the Roundhouse', country: 'South Africa', country_code: 'ZA', latitude: -33.9419, longitude: 18.3783, manualId: 'manual:cape-town:lawns-roundhouse' },
  { pattern: /pot luck club/i, name: 'The Pot Luck Club', country: 'South Africa', country_code: 'ZA', latitude: -33.9275, longitude: 18.4574, manualId: 'manual:cape-town:pot-luck-club' },

  { pattern: /sydney opera house/i, name: 'Sydney Opera House', country: 'Australia', country_code: 'AU', latitude: -33.85678, longitude: 151.2153, manualId: 'manual:sydney:opera-house' },
  { pattern: /city extra/i, name: 'City Extra 24 Hour Restaurant', country: 'Australia', country_code: 'AU', latitude: -33.86162, longitude: 151.21197, manualId: 'manual:sydney:city-extra' },
  { pattern: /rocks discovery/i, name: 'The Rocks Discovery Museum', country: 'Australia', country_code: 'AU', latitude: -33.85902, longitude: 151.20875, manualId: 'manual:sydney:rocks-discovery-museum' },
  { pattern: /museum of contemporary art/i, name: 'Museum of Contemporary Art Australia', country: 'Australia', country_code: 'AU', latitude: -33.85992, longitude: 151.20903, manualId: 'manual:sydney:mca' },
  { pattern: /mures circular quay|circular quay/i, name: 'Mures Circular Quay', country: 'Australia', country_code: 'AU', latitude: -33.86165, longitude: 151.21215, manualId: 'manual:sydney:mures-circular-quay' },
  { pattern: /bondi icebergs/i, name: 'Bondi Icebergs Club', country: 'Australia', country_code: 'AU', latitude: -33.89502, longitude: 151.27432, manualId: 'manual:sydney:bondi-icebergs' },
  { pattern: /bills bondi/i, name: 'Bills Bondi', country: 'Australia', country_code: 'AU', latitude: -33.88979, longitude: 151.27011, manualId: 'manual:sydney:bills-bondi' },
  { pattern: /bondi to bronte/i, name: 'Bondi to Bronte Coastal Walk', country: 'Australia', country_code: 'AU', latitude: -33.89954, longitude: 151.2727, manualId: 'manual:sydney:bondi-bronte-walk' },
  { pattern: /bronte baths/i, name: 'Bronte Baths', country: 'Australia', country_code: 'AU', latitude: -33.90453, longitude: 151.26867, manualId: 'manual:sydney:bronte-baths' },
  { pattern: /fish at the rocks/i, name: 'Fish At The Rocks', country: 'Australia', country_code: 'AU', latitude: -33.85867, longitude: 151.2082, manualId: 'manual:sydney:fish-at-the-rocks' },
  { pattern: /manly ferry|manly wharf/i, name: 'Manly Wharf', country: 'Australia', country_code: 'AU', latitude: -33.8002, longitude: 151.28448, manualId: 'manual:sydney:manly-wharf' },
  { pattern: /manly pavilion/i, name: 'Manly Pavilion', country: 'Australia', country_code: 'AU', latitude: -33.79962, longitude: 151.28462, manualId: 'manual:sydney:manly-pavilion' },
  { pattern: /shelly beach/i, name: 'Shelly Beach', country: 'Australia', country_code: 'AU', latitude: -33.80086, longitude: 151.29865, manualId: 'manual:sydney:shelly-beach' },
  { pattern: /north head/i, name: 'North Head Lookout', country: 'Australia', country_code: 'AU', latitude: -33.81362, longitude: 151.30031, manualId: 'manual:sydney:north-head-lookout' },
  { pattern: /sake restaurant.*rocks|sake.*rocks/i, name: 'Sake Restaurant & Bar The Rocks', country: 'Australia', country_code: 'AU', latitude: -33.85882, longitude: 151.20878, manualId: 'manual:sydney:sake-the-rocks' },
  { pattern: /royal botanic garden/i, name: 'Royal Botanic Garden Sydney', country: 'Australia', country_code: 'AU', latitude: -33.86419, longitude: 151.21657, manualId: 'manual:sydney:royal-botanic-garden' },
  { pattern: /paddington reservoir/i, name: 'Paddington Reservoir Gardens', country: 'Australia', country_code: 'AU', latitude: -33.8844, longitude: 151.22932, manualId: 'manual:sydney:paddington-reservoir' },
  { pattern: /art gallery of new south wales/i, name: 'Art Gallery of New South Wales', country: 'Australia', country_code: 'AU', latitude: -33.8688, longitude: 151.2173, manualId: 'manual:sydney:art-gallery-nsw' },
  { pattern: /grounds of alexandria/i, name: 'The Grounds of Alexandria', country: 'Australia', country_code: 'AU', latitude: -33.91078, longitude: 151.19487, manualId: 'manual:sydney:grounds-alexandria' },
  { pattern: /saint peter/i, name: 'Saint Peter', country: 'Australia', country_code: 'AU', latitude: -33.88984, longitude: 151.23049, manualId: 'manual:sydney:saint-peter' },

  { pattern: /scholarhio/i, name: 'Scholarhio', country: 'Greece', country_code: 'GR', latitude: 37.97224, longitude: 23.73033, manualId: 'manual:athens:scholarhio' },
  { pattern: /anafiotika cafe/i, name: 'Anafiotika Cafe Restaurant', country: 'Greece', country_code: 'GR', latitude: 37.97316, longitude: 23.7283, manualId: 'manual:athens:anafiotika-cafe' },
  { pattern: /karamanlidika/i, name: 'Karamanlidika', country: 'Greece', country_code: 'GR', latitude: 37.97964, longitude: 23.72454, manualId: 'manual:athens:karamanlidika' },
  { pattern: /couleur locale/i, name: 'Couleur Locale', country: 'Greece', country_code: 'GR', latitude: 37.97625, longitude: 23.72424, manualId: 'manual:athens:couleur-locale' },
  { pattern: /canal caf[eé]/i, name: 'Canal Cafe', country: 'Greece', country_code: 'GR', latitude: 37.94041, longitude: 23.69095, manualId: 'manual:athens:canal-cafe' },
  { pattern: /istioploikos/i, name: 'Istioploikos', country: 'Greece', country_code: 'GR', latitude: 37.92951, longitude: 23.6881, manualId: 'manual:athens:istioploikos' },
  { pattern: /national archaeological museum/i, name: 'National Archaeological Museum', country: 'Greece', country_code: 'GR', latitude: 37.98901, longitude: 23.73276, manualId: 'manual:athens:national-archaeological-museum' },
  { pattern: /atitamos/i, name: 'Atitamos', country: 'Greece', country_code: 'GR', latitude: 37.98637, longitude: 23.7331, manualId: 'manual:athens:atitamos' },
  { pattern: /^national garden$/i, name: 'National Garden', country: 'Greece', country_code: 'GR', latitude: 37.97393, longitude: 23.73624, manualId: 'manual:athens:national-garden' },
  { pattern: /oikeio/i, name: 'Oikeio', country: 'Greece', country_code: 'GR', latitude: 37.97888, longitude: 23.74128, manualId: 'manual:athens:oikeio' },
  { pattern: /temple of olympian zeus/i, name: 'Temple of Olympian Zeus', country: 'Greece', country_code: 'GR', latitude: 37.96931, longitude: 23.7331, manualId: 'manual:athens:temple-olympian-zeus' },
  { pattern: /to kati allo/i, name: 'To Kati Allo', country: 'Greece', country_code: 'GR', latitude: 37.96759, longitude: 23.72704, manualId: 'manual:athens:to-kati-allo' },
  { pattern: /philopappos/i, name: 'Philopappos Hill', country: 'Greece', country_code: 'GR', latitude: 37.96787, longitude: 23.72182, manualId: 'manual:athens:philopappos-hill' },
  { pattern: /dionysos zonar/i, name: "Dionysos Zonar's", country: 'Greece', country_code: 'GR', latitude: 37.96814, longitude: 23.72565, manualId: 'manual:athens:dionysos-zonars' },

  { pattern: /copacabana beach/i, name: 'Copacabana Beach', country: 'Brazil', country_code: 'BR', latitude: -22.97111, longitude: -43.18223, manualId: 'manual:rio:copacabana-beach' },
  { pattern: /marius degustare/i, name: 'Restaurante Marius Degustare', country: 'Brazil', country_code: 'BR', latitude: -22.96479, longitude: -43.17403, manualId: 'manual:rio:marius-degustare' },
  { pattern: /sugarloaf|p[aã]o de a[cç][uú]car/i, name: 'Sugarloaf Mountain', country: 'Brazil', country_code: 'BR', latitude: -22.94865, longitude: -43.15645, manualId: 'manual:rio:sugarloaf-mountain' },
  { pattern: /bar urca/i, name: 'Bar Urca', country: 'Brazil', country_code: 'BR', latitude: -22.94434, longitude: -43.16119, manualId: 'manual:rio:bar-urca' },
  { pattern: /christ the redeemer|cristo redentor/i, name: 'Christ the Redeemer', country: 'Brazil', country_code: 'BR', latitude: -22.95192, longitude: -43.21049, manualId: 'manual:rio:christ-the-redeemer' },
  { pattern: /apraz[ií]vel/i, name: 'Aprazível', country: 'Brazil', country_code: 'BR', latitude: -22.91868, longitude: -43.18767, manualId: 'manual:rio:aprazivel' },
  { pattern: /escadaria selar[oó]n/i, name: 'Escadaria Selarón', country: 'Brazil', country_code: 'BR', latitude: -22.91542, longitude: -43.1795, manualId: 'manual:rio:escadaria-selaron' },
  { pattern: /carioca aqueduct|arcos da lapa/i, name: 'Carioca Aqueduct', country: 'Brazil', country_code: 'BR', latitude: -22.91254, longitude: -43.17972, manualId: 'manual:rio:carioca-aqueduct' },
  { pattern: /rio scenarium/i, name: 'Rio Scenarium', country: 'Brazil', country_code: 'BR', latitude: -22.90938, longitude: -43.18234, manualId: 'manual:rio:rio-scenarium' },
  { pattern: /ipanema beach/i, name: 'Ipanema Beach', country: 'Brazil', country_code: 'BR', latitude: -22.98625, longitude: -43.20483, manualId: 'manual:rio:ipanema-beach' },
  { pattern: /garota de ipanema/i, name: 'Garota de Ipanema', country: 'Brazil', country_code: 'BR', latitude: -22.98462, longitude: -43.20372, manualId: 'manual:rio:garota-de-ipanema' },
  { pattern: /rodrigo de freitas|lagoa/i, name: 'Rodrigo de Freitas Lagoon', country: 'Brazil', country_code: 'BR', latitude: -22.9712, longitude: -43.21285, manualId: 'manual:rio:rodrigo-de-freitas-lagoon' },
  { pattern: /arpoador/i, name: 'Arpoador', country: 'Brazil', country_code: 'BR', latitude: -22.98852, longitude: -43.19178, manualId: 'manual:rio:arpoador' },
  { pattern: /zaz[aá]/i, name: 'Zazá Bistrô Tropical', country: 'Brazil', country_code: 'BR', latitude: -22.98449, longitude: -43.20254, manualId: 'manual:rio:zaza-bistro' },
  { pattern: /jardim bot[aâ]nico do rio/i, name: 'Jardim Botânico do Rio de Janeiro', country: 'Brazil', country_code: 'BR', latitude: -22.96707, longitude: -43.22343, manualId: 'manual:rio:jardim-botanico' },
  { pattern: /casa camolese/i, name: 'Casa Camolese', country: 'Brazil', country_code: 'BR', latitude: -22.96639, longitude: -43.22234, manualId: 'manual:rio:casa-camolese' },
  { pattern: /vista chinesa/i, name: 'Vista Chinesa', country: 'Brazil', country_code: 'BR', latitude: -22.9721, longitude: -43.27902, manualId: 'manual:rio:vista-chinesa' },
  { pattern: /brewteco/i, name: 'Brewteco Botafogo', country: 'Brazil', country_code: 'BR', latitude: -22.94945, longitude: -43.18489, manualId: 'manual:rio:brewteco-botafogo' },
  { pattern: /\bbip bip\b/i, name: 'Bip Bip', country: 'Brazil', country_code: 'BR', latitude: -22.97441, longitude: -43.19049, manualId: 'manual:rio:bip-bip' },
  { pattern: /museu do amanh[aã]/i, name: 'Museu do Amanhã', country: 'Brazil', country_code: 'BR', latitude: -22.89429, longitude: -43.1793, manualId: 'manual:rio:museu-do-amanha' },
  { pattern: /cais do oriente/i, name: 'Cais do Oriente', country: 'Brazil', country_code: 'BR', latitude: -22.89533, longitude: -43.17998, manualId: 'manual:rio:cais-do-oriente' },
  { pattern: /mirante do leblon/i, name: 'Mirante do Leblon', country: 'Brazil', country_code: 'BR', latitude: -22.99327, longitude: -43.23358, manualId: 'manual:rio:mirante-do-leblon' },
  { pattern: /boteco belmonte/i, name: 'Boteco Belmonte Leblon', country: 'Brazil', country_code: 'BR', latitude: -22.98456, longitude: -43.22235, manualId: 'manual:rio:boteco-belmonte-leblon' },

  { pattern: /kiyomizu-?dera/i, name: 'Kiyomizu-dera', country: 'Japan', country_code: 'JP', latitude: 34.99486, longitude: 135.78505, manualId: 'manual:kyoto:kiyomizu-dera' },
  { pattern: /nishiki market/i, name: 'Nishiki Market', country: 'Japan', country_code: 'JP', latitude: 35.00503, longitude: 135.76477, manualId: 'manual:kyoto:nishiki-market' },
  { pattern: /yasaka shrine/i, name: 'Yasaka Shrine', country: 'Japan', country_code: 'JP', latitude: 35.00366, longitude: 135.77855, manualId: 'manual:kyoto:yasaka-shrine' },
  { pattern: /salon de muge/i, name: 'Salon de Muge', country: 'Japan', country_code: 'JP', latitude: 35.00474, longitude: 135.77575, manualId: 'manual:kyoto:salon-de-muge' },
  { pattern: /tenryu-?ji/i, name: 'Tenryu-ji Temple', country: 'Japan', country_code: 'JP', latitude: 35.01596, longitude: 135.67356, manualId: 'manual:kyoto:tenryu-ji' },
  { pattern: /arashiyama yoshimura/i, name: 'Arashiyama Yoshimura', country: 'Japan', country_code: 'JP', latitude: 35.01359, longitude: 135.67774, manualId: 'manual:kyoto:arashiyama-yoshimura' },
  { pattern: /kinkaku-?ji|golden pavilion/i, name: 'Kinkaku-ji', country: 'Japan', country_code: 'JP', latitude: 35.03937, longitude: 135.72924, manualId: 'manual:kyoto:kinkaku-ji' },
  { pattern: /kyoto gogyo/i, name: 'Kyoto Gogyo', country: 'Japan', country_code: 'JP', latitude: 35.00729, longitude: 135.76213, manualId: 'manual:kyoto:gogyo' },
  { pattern: /fushimi inari/i, name: 'Fushimi Inari Taisha', country: 'Japan', country_code: 'JP', latitude: 34.96714, longitude: 135.77267, manualId: 'manual:kyoto:fushimi-inari' },
  { pattern: /sushi no musashi/i, name: 'Sushi no Musashi Kyoto Station Hachijo Entrance', country: 'Japan', country_code: 'JP', latitude: 34.98479, longitude: 135.75913, manualId: 'manual:kyoto:sushi-no-musashi' },
  { pattern: /kennin-?ji/i, name: 'Kennin-ji', country: 'Japan', country_code: 'JP', latitude: 35.00085, longitude: 135.77403, manualId: 'manual:kyoto:kennin-ji' },
  { pattern: /inoda coffee/i, name: 'Inoda Coffee Honten', country: 'Japan', country_code: 'JP', latitude: 35.00867, longitude: 135.76246, manualId: 'manual:kyoto:inoda-coffee-honten' },

  { pattern: /crate caf[eé]/i, name: 'Crate Cafe', country: 'Indonesia', country_code: 'ID', latitude: -8.64929, longitude: 115.13858, manualId: 'manual:bali:crate-cafe' },
  { pattern: /batu bolong beach/i, name: 'Batu Bolong Beach', country: 'Indonesia', country_code: 'ID', latitude: -8.6573, longitude: 115.13012, manualId: 'manual:bali:batu-bolong-beach' },
  { pattern: /\bzin caf[eé]/i, name: 'ZIN Cafe', country: 'Indonesia', country_code: 'ID', latitude: -8.6535, longitude: 115.13096, manualId: 'manual:bali:zin-cafe' },
  { pattern: /ji restaurant/i, name: 'Ji Restaurant Bali', country: 'Indonesia', country_code: 'ID', latitude: -8.65368, longitude: 115.13005, manualId: 'manual:bali:ji-restaurant' },
  { pattern: /\bbaked\.?\s*berawa/i, name: 'Baked Berawa', country: 'Indonesia', country_code: 'ID', latitude: -8.65831, longitude: 115.14695, manualId: 'manual:bali:baked-berawa' },
  { pattern: /tanah lot/i, name: 'Tanah Lot Temple', country: 'Indonesia', country_code: 'ID', latitude: -8.62121, longitude: 115.08681, manualId: 'manual:bali:tanah-lot' },
  { pattern: /milu by nook/i, name: 'Milu By Nook', country: 'Indonesia', country_code: 'ID', latitude: -8.66296, longitude: 115.14575, manualId: 'manual:bali:milu-by-nook' },
  { pattern: /the lawn canggu/i, name: 'The Lawn Canggu', country: 'Indonesia', country_code: 'ID', latitude: -8.65622, longitude: 115.12994, manualId: 'manual:bali:the-lawn-canggu' },
  { pattern: /suka espresso ubud/i, name: 'Suka Espresso Ubud', country: 'Indonesia', country_code: 'ID', latitude: -8.51734, longitude: 115.26263, manualId: 'manual:bali:suka-espresso-ubud' },
  { pattern: /goa gajah/i, name: 'Goa Gajah', country: 'Indonesia', country_code: 'ID', latitude: -8.52385, longitude: 115.28672, manualId: 'manual:bali:goa-gajah' },
  { pattern: /seniman coffee/i, name: 'Seniman Coffee Studio', country: 'Indonesia', country_code: 'ID', latitude: -8.50529, longitude: 115.26477, manualId: 'manual:bali:seniman-coffee' },
  { pattern: /campuhan ridge/i, name: 'Campuhan Ridge Walk', country: 'Indonesia', country_code: 'ID', latitude: -8.49912, longitude: 115.25539, manualId: 'manual:bali:campuhan-ridge' },
  { pattern: /hujan locale/i, name: 'Hujan Locale', country: 'Indonesia', country_code: 'ID', latitude: -8.50731, longitude: 115.26465, manualId: 'manual:bali:hujan-locale' },
  { pattern: /loft uluwatu/i, name: 'The Loft Uluwatu', country: 'Indonesia', country_code: 'ID', latitude: -8.81216, longitude: 115.11426, manualId: 'manual:bali:the-loft-uluwatu' },
  { pattern: /padang padang/i, name: 'Padang Padang Beach', country: 'Indonesia', country_code: 'ID', latitude: -8.81042, longitude: 115.1025, manualId: 'manual:bali:padang-padang' },
  { pattern: /drifter surf/i, name: 'Drifter Surf Shop Cafe And Gallery', country: 'Indonesia', country_code: 'ID', latitude: -8.81377, longitude: 115.11954, manualId: 'manual:bali:drifter-surf' },
  { pattern: /uluwatu temple/i, name: 'Uluwatu Temple', country: 'Indonesia', country_code: 'ID', latitude: -8.82914, longitude: 115.08493, manualId: 'manual:bali:uluwatu-temple' },
  { pattern: /single fin bali/i, name: 'Single Fin Bali', country: 'Indonesia', country_code: 'ID', latitude: -8.81447, longitude: 115.08928, manualId: 'manual:bali:single-fin' },
  { pattern: /revolver espresso/i, name: 'Revolver Espresso', country: 'Indonesia', country_code: 'ID', latitude: -8.68465, longitude: 115.15892, manualId: 'manual:bali:revolver-espresso' },
  { pattern: /petitenget temple/i, name: 'Petitenget Temple', country: 'Indonesia', country_code: 'ID', latitude: -8.68189, longitude: 115.15313, manualId: 'manual:bali:petitenget-temple' },
  { pattern: /kynd community/i, name: 'KYND Community', country: 'Indonesia', country_code: 'ID', latitude: -8.68072, longitude: 115.16129, manualId: 'manual:bali:kynd-community' },
  { pattern: /seminyak beach/i, name: 'Seminyak Beach', country: 'Indonesia', country_code: 'ID', latitude: -8.69134, longitude: 115.15859, manualId: 'manual:bali:seminyak-beach' },
  { pattern: /la lucciola/i, name: 'La Lucciola', country: 'Indonesia', country_code: 'ID', latitude: -8.67924, longitude: 115.15387, manualId: 'manual:bali:la-lucciola' },

  { pattern: /giraffe centre|giraffe center/i, name: 'Giraffe Centre', country: 'Kenya', country_code: 'KE', latitude: -1.37658, longitude: 36.74412, manualId: 'manual:nairobi:giraffe-centre' },
  { pattern: /tamambo karen/i, name: 'Tamambo Karen Blixen', country: 'Kenya', country_code: 'KE', latitude: -1.35113, longitude: 36.71022, manualId: 'manual:nairobi:tamambo-karen-blixen' },
  { pattern: /karen blixen museum/i, name: 'Karen Blixen Museum', country: 'Kenya', country_code: 'KE', latitude: -1.35187, longitude: 36.71061, manualId: 'manual:nairobi:karen-blixen-museum' },
  { pattern: /kazuri beads/i, name: 'Kazuri Beads Factory', country: 'Kenya', country_code: 'KE', latitude: -1.34236, longitude: 36.71392, manualId: 'manual:nairobi:kazuri-beads' },
  { pattern: /cultiva farm/i, name: 'Cultiva Farm Kenya', country: 'Kenya', country_code: 'KE', latitude: -1.36331, longitude: 36.73178, manualId: 'manual:nairobi:cultiva-farm' },
  { pattern: /nairobi national museum/i, name: 'Nairobi National Museum', country: 'Kenya', country_code: 'KE', latitude: -1.27399, longitude: 36.81578, manualId: 'manual:nairobi:national-museum' },
  { pattern: /museum hill cafe/i, name: 'Museum Hill Cafe', country: 'Kenya', country_code: 'KE', latitude: -1.27442, longitude: 36.81523, manualId: 'manual:nairobi:museum-hill-cafe' },
  { pattern: /maasai market.*village market/i, name: 'The Maasai Market at Village Market', country: 'Kenya', country_code: 'KE', latitude: -1.22972, longitude: 36.80517, manualId: 'manual:nairobi:maasai-market-village' },
  { pattern: /banana hill art/i, name: 'Banana Hill Art Gallery', country: 'Kenya', country_code: 'KE', latitude: -1.16785, longitude: 36.75565, manualId: 'manual:nairobi:banana-hill-art-gallery' },
  { pattern: /cj'?s village market/i, name: "CJ's Village Market", country: 'Kenya', country_code: 'KE', latitude: -1.22923, longitude: 36.80538, manualId: 'manual:nairobi:cjs-village-market' },
  { pattern: /nairobi national park.*gate/i, name: 'Nairobi National Park Main Gate', country: 'Kenya', country_code: 'KE', latitude: -1.34558, longitude: 36.82121, manualId: 'manual:nairobi:national-park-main-gate' },
  { pattern: /muguga green/i, name: 'Muguga Green Restaurant', country: 'Kenya', country_code: 'KE', latitude: -1.2892, longitude: 36.78296, manualId: 'manual:nairobi:muguga-green' },
  { pattern: /bomas of kenya/i, name: 'Bomas of Kenya', country: 'Kenya', country_code: 'KE', latitude: -1.33663, longitude: 36.76773, manualId: 'manual:nairobi:bomas-of-kenya' },
  { pattern: /nyayo monument/i, name: 'Nyayo Monument', country: 'Kenya', country_code: 'KE', latitude: -1.28989, longitude: 36.82008, manualId: 'manual:nairobi:nyayo-monument' },
  { pattern: /talisman restaurant/i, name: 'Talisman Restaurant', country: 'Kenya', country_code: 'KE', latitude: -1.32729, longitude: 36.71218, manualId: 'manual:nairobi:talisman' },
  { pattern: /karura forest/i, name: 'Karura Forest Sigiria Entrance', country: 'Kenya', country_code: 'KE', latitude: -1.23489, longitude: 36.81709, manualId: 'manual:nairobi:karura-forest-sigiria' },
  { pattern: /river cafe/i, name: 'River Cafe', country: 'Kenya', country_code: 'KE', latitude: -1.23445, longitude: 36.81657, manualId: 'manual:nairobi:river-cafe' },
  { pattern: /house of treasures/i, name: 'House of Treasures Emporium', country: 'Kenya', country_code: 'KE', latitude: -1.2539, longitude: 36.80691, manualId: 'manual:nairobi:house-of-treasures' },
  { pattern: /fairview coffee/i, name: 'Fairview Coffee Estate', country: 'Kenya', country_code: 'KE', latitude: -1.20873, longitude: 36.77434, manualId: 'manual:nairobi:fairview-coffee-estate' },
  { pattern: /hero restaurant/i, name: 'Hero Restaurant', country: 'Kenya', country_code: 'KE', latitude: -1.30023, longitude: 36.78432, manualId: 'manual:nairobi:hero-restaurant' },

  { pattern: /national museum of natural history/i, name: 'National Museum of Natural History', country: 'United States', country_code: 'US', latitude: 38.89127, longitude: -77.02607, manualId: 'manual:washington-dc:natural-history-museum' },
  { pattern: /mitsitam/i, name: 'Mitsitam Native Foods Cafe', country: 'United States', country_code: 'US', latitude: 38.88825, longitude: -77.01661, manualId: 'manual:washington-dc:mitsitam' },
  { pattern: /national museum of the american indian/i, name: 'National Museum of the American Indian', country: 'United States', country_code: 'US', latitude: 38.88811, longitude: -77.01647, manualId: 'manual:washington-dc:american-indian-museum' },
  { pattern: /lincoln memorial/i, name: 'Lincoln Memorial', country: 'United States', country_code: 'US', latitude: 38.88927, longitude: -77.05018, manualId: 'manual:washington-dc:lincoln-memorial' },
  { pattern: /founding farmers/i, name: 'Founding Farmers DC', country: 'United States', country_code: 'US', latitude: 38.90036, longitude: -77.04443, manualId: 'manual:washington-dc:founding-farmers' },
  { pattern: /national air and space museum|smithsonian national air/i, name: 'National Air and Space Museum', country: 'United States', country_code: 'US', latitude: 38.88816, longitude: -77.01987, manualId: 'manual:washington-dc:air-space-museum' },
  { pattern: /sweet home cafe/i, name: 'Sweet Home Cafe', country: 'United States', country_code: 'US', latitude: 38.89104, longitude: -77.03274, manualId: 'manual:washington-dc:sweet-home-cafe' },
  { pattern: /united states capitol visitor/i, name: 'United States Capitol Visitor Center', country: 'United States', country_code: 'US', latitude: 38.88994, longitude: -77.00892, manualId: 'manual:washington-dc:capitol-visitor-center' },
  { pattern: /library of congress/i, name: 'Library of Congress', country: 'United States', country_code: 'US', latitude: 38.88868, longitude: -77.00472, manualId: 'manual:washington-dc:library-of-congress' },
  { pattern: /ted'?s bulletin/i, name: "Ted's Bulletin Capitol Hill", country: 'United States', country_code: 'US', latitude: 38.88492, longitude: -76.99569, manualId: 'manual:washington-dc:teds-bulletin' },
  { pattern: /national museum of american history/i, name: 'National Museum of American History', country: 'United States', country_code: 'US', latitude: 38.89128, longitude: -77.03004, manualId: 'manual:washington-dc:american-history-museum' },
  { pattern: /pavilion cafe/i, name: 'Pavilion Cafe', country: 'United States', country_code: 'US', latitude: 38.88949, longitude: -77.02286, manualId: 'manual:washington-dc:pavilion-cafe' },
  { pattern: /national gallery of art/i, name: 'National Gallery of Art', country: 'United States', country_code: 'US', latitude: 38.8913, longitude: -77.01988, manualId: 'manual:washington-dc:national-gallery' },
  { pattern: /white house visitor center/i, name: 'White House Visitor Center', country: 'United States', country_code: 'US', latitude: 38.89649, longitude: -77.03302, manualId: 'manual:washington-dc:white-house-visitor-center' },
  { pattern: /old ebbitt/i, name: 'Old Ebbitt Grill', country: 'United States', country_code: 'US', latitude: 38.89773, longitude: -77.03355, manualId: 'manual:washington-dc:old-ebbitt-grill' },

  { pattern: /diodos archaias agoras/i, name: 'Diodos Archaias Agoras', country: 'Greece', country_code: 'GR', latitude: 37.9741, longitude: 23.72293, manualId: 'manual:athens:diodos-archaias-agoras' },
  { pattern: /oinomageireio epirus|epirus/i, name: 'Oinomageireio Epirus', country: 'Greece', country_code: 'GR', latitude: 37.97999, longitude: 23.72626, manualId: 'manual:athens:oinomageireio-epirus' },
  { pattern: /psarades/i, name: 'Psarades', country: 'Greece', country_code: 'GR', latitude: 37.93068, longitude: 23.68649, manualId: 'manual:athens:psarades' },
  { pattern: /to lokali/i, name: 'To Lokali', country: 'Greece', country_code: 'GR', latitude: 37.97692, longitude: 23.72527, manualId: 'manual:athens:to-lokali' },
  { pattern: /roman agora/i, name: 'Roman Agora of Athens', country: 'Greece', country_code: 'GR', latitude: 37.97405, longitude: 23.72634, manualId: 'manual:athens:roman-agora' },
  { pattern: /little kook/i, name: 'Little Kook', country: 'Greece', country_code: 'GR', latitude: 37.97729, longitude: 23.72426, manualId: 'manual:athens:little-kook' },
  { pattern: /temple of hephaestus/i, name: 'Temple of Hephaestus', country: 'Greece', country_code: 'GR', latitude: 37.97564, longitude: 23.72145, manualId: 'manual:athens:temple-hephaestus' },
  { pattern: /\bkuzina\b/i, name: 'Kuzina', country: 'Greece', country_code: 'GR', latitude: 37.9754, longitude: 23.72333, manualId: 'manual:athens:kuzina' },

  { pattern: /galeto sat/i, name: "Galeto Sat's", country: 'Brazil', country_code: 'BR', latitude: -22.96334, longitude: -43.17437, manualId: 'manual:rio:galeto-sats' },
  { pattern: /boteco colarinho/i, name: 'Boteco Colarinho', country: 'Brazil', country_code: 'BR', latitude: -22.95322, longitude: -43.18574, manualId: 'manual:rio:boteco-colarinho' },
  { pattern: /bar do mineiro/i, name: 'Bar do Mineiro', country: 'Brazil', country_code: 'BR', latitude: -22.92009, longitude: -43.18793, manualId: 'manual:rio:bar-do-mineiro' },
  { pattern: /caf[eé] du centre/i, name: 'Café du Centre', country: 'Brazil', country_code: 'BR', latitude: -22.96601, longitude: -43.22313, manualId: 'manual:rio:cafe-du-centre' },
  { pattern: /parque lage/i, name: 'Parque Lage', country: 'Brazil', country_code: 'BR', latitude: -22.96073, longitude: -43.21159, manualId: 'manual:rio:parque-lage' },
  { pattern: /\bjobi\b/i, name: 'Jobi', country: 'Brazil', country_code: 'BR', latitude: -22.98462, longitude: -43.22304, manualId: 'manual:rio:jobi' },
  { pattern: /museu de arte contempor[aâ]nea de niter[oó]i/i, name: 'Museu de Arte Contemporânea de Niterói', country: 'Brazil', country_code: 'BR', latitude: -22.90782, longitude: -43.12575, manualId: 'manual:rio:mac-niteroi' },
  { pattern: /gruta de santo ant[oô]nio/i, name: 'Gruta de Santo Antônio', country: 'Brazil', country_code: 'BR', latitude: -22.90042, longitude: -43.12365, manualId: 'manual:rio:gruta-santo-antonio' },
  { pattern: /mirante dona marta/i, name: 'Mirante Dona Marta', country: 'Brazil', country_code: 'BR', latitude: -22.94583, longitude: -43.19639, manualId: 'manual:rio:mirante-dona-marta' },

  { pattern: /kodai-?ji/i, name: 'Kodai-ji Temple', country: 'Japan', country_code: 'JP', latitude: 35.00004, longitude: 135.78121, manualId: 'manual:kyoto:kodai-ji' },
  { pattern: /saryo tsujiri/i, name: 'Saryo Tsujiri Gion Honten', country: 'Japan', country_code: 'JP', latitude: 35.0039, longitude: 135.77493, manualId: 'manual:kyoto:saryo-tsujiri-gion' },
  { pattern: /otagi nenbutsu/i, name: 'Otagi Nenbutsu-ji', country: 'Japan', country_code: 'JP', latitude: 35.03118, longitude: 135.66134, manualId: 'manual:kyoto:otagi-nenbutsu-ji' },
  { pattern: /excafe arashiyama|ex\-?cafe arashiyama/i, name: 'eXcafe Arashiyama', country: 'Japan', country_code: 'JP', latitude: 35.015, longitude: 135.67736, manualId: 'manual:kyoto:excafe-arashiyama' },
  { pattern: /demachi futaba/i, name: 'Demachi Futaba', country: 'Japan', country_code: 'JP', latitude: 35.03009, longitude: 135.7721, manualId: 'manual:kyoto:demachi-futaba' },
  { pattern: /ginkaku-?ji/i, name: 'Ginkaku-ji', country: 'Japan', country_code: 'JP', latitude: 35.02702, longitude: 135.79821, manualId: 'manual:kyoto:ginkaku-ji' },
  { pattern: /omen ginkaku/i, name: 'Omen Ginkaku-ji', country: 'Japan', country_code: 'JP', latitude: 35.02634, longitude: 135.79336, manualId: 'manual:kyoto:omen-ginkaku-ji' },

  { pattern: /saraswati temple/i, name: 'Saraswati Temple', country: 'Indonesia', country_code: 'ID', latitude: -8.50688, longitude: 115.26248, manualId: 'manual:bali:saraswati-temple' },
  { pattern: /soul on the beach/i, name: 'Soul on the Beach', country: 'Indonesia', country_code: 'ID', latitude: -8.70777, longitude: 115.26036, manualId: 'manual:bali:soul-on-the-beach' },
  { pattern: /sanur beach/i, name: 'Sanur Beach', country: 'Indonesia', country_code: 'ID', latitude: -8.692, longitude: 115.26322, manualId: 'manual:bali:sanur-beach' },
  { pattern: /pura blanjong/i, name: 'Pura Blanjong', country: 'Indonesia', country_code: 'ID', latitude: -8.70644, longitude: 115.25632, manualId: 'manual:bali:pura-blanjong' },
  { pattern: /massimo italian/i, name: 'MASSIMO Italian Restaurant', country: 'Indonesia', country_code: 'ID', latitude: -8.70647, longitude: 115.25829, manualId: 'manual:bali:massimo' },

  { pattern: /^nairobi national park$/i, name: 'Nairobi National Park', country: 'Kenya', country_code: 'KE', latitude: -1.37333, longitude: 36.85889, manualId: 'manual:nairobi:national-park' },
  { pattern: /matbronze/i, name: 'Matbronze Cafe', country: 'Kenya', country_code: 'KE', latitude: -1.38616, longitude: 36.75322, manualId: 'manual:nairobi:matbronze-cafe' },
  { pattern: /nairobi gallery/i, name: 'Nairobi Gallery', country: 'Kenya', country_code: 'KE', latitude: -1.28874, longitude: 36.81745, manualId: 'manual:nairobi:gallery' },
  { pattern: /kenyatta international|kicc/i, name: 'Kenyatta International Convention Centre', country: 'Kenya', country_code: 'KE', latitude: -1.28825, longitude: 36.82316, manualId: 'manual:nairobi:kicc' },
  { pattern: /balcony bar nairobi/i, name: 'The Balcony Bar Nairobi', country: 'Kenya', country_code: 'KE', latitude: -1.28659, longitude: 36.81788, manualId: 'manual:nairobi:balcony-bar' },
  { pattern: /spinners web/i, name: 'Spinners Web Kenya', country: 'Kenya', country_code: 'KE', latitude: -1.23718, longitude: 36.78335, manualId: 'manual:nairobi:spinners-web' },
  { pattern: /\binti\b/i, name: 'INTI - A Nikkei Experience', country: 'Kenya', country_code: 'KE', latitude: -1.26463, longitude: 36.8021, manualId: 'manual:nairobi:inti' },
  { pattern: /godown arts/i, name: 'The GoDown Arts Centre', country: 'Kenya', country_code: 'KE', latitude: -1.30624, longitude: 36.82929, manualId: 'manual:nairobi:godown-arts' },
  { pattern: /sarit centre|sarit center/i, name: 'Sarit Centre', country: 'Kenya', country_code: 'KE', latitude: -1.26174, longitude: 36.80211, manualId: 'manual:nairobi:sarit-centre' },
  { pattern: /about thyme/i, name: 'About Thyme Restaurant', country: 'Kenya', country_code: 'KE', latitude: -1.26363, longitude: 36.80365, manualId: 'manual:nairobi:about-thyme' },

  { pattern: /capital grille/i, name: 'The Capital Grille', country: 'United States', country_code: 'US', latitude: 38.89691, longitude: -77.02887, manualId: 'manual:washington-dc:capital-grille' },
  { pattern: /carmine'?s/i, name: "Carmine's Italian Restaurant", country: 'United States', country_code: 'US', latitude: 38.89779, longitude: -77.02314, manualId: 'manual:washington-dc:carmines' },
  { pattern: /international spy museum/i, name: 'International Spy Museum', country: 'United States', country_code: 'US', latitude: 38.88382, longitude: -77.02574, manualId: 'manual:washington-dc:spy-museum' },
  { pattern: /farmers fishers bakers/i, name: 'Farmers Fishers Bakers', country: 'United States', country_code: 'US', latitude: 38.9018, longitude: -77.06002, manualId: 'manual:washington-dc:farmers-fishers-bakers' },
  { pattern: /martin luther king.*memorial/i, name: 'Martin Luther King, Jr. Memorial', country: 'United States', country_code: 'US', latitude: 38.88623, longitude: -77.04423, manualId: 'manual:washington-dc:mlk-memorial' },
  { pattern: /franklin delano roosevelt|fdr memorial/i, name: 'Franklin Delano Roosevelt Memorial', country: 'United States', country_code: 'US', latitude: 38.88327, longitude: -77.04302, manualId: 'manual:washington-dc:fdr-memorial' },

  { pattern: /^kostas(?:,|$)/i, name: 'Kostas Souvlaki', country: 'Greece', country_code: 'GR', latitude: 37.97616, longitude: 23.728, manualId: 'manual:athens:kostas-souvlaki' },
  { pattern: /national observatory of athens/i, name: 'National Observatory of Athens', country: 'Greece', country_code: 'GR', latitude: 37.97314, longitude: 23.71734, manualId: 'manual:athens:national-observatory' },
  { pattern: /oineas/i, name: 'Oineas Restaurant', country: 'Greece', country_code: 'GR', latitude: 37.97843, longitude: 23.72333, manualId: 'manual:athens:oineas' },
  { pattern: /^ark(?:,|$)/i, name: 'Ark', country: 'Greece', country_code: 'GR', latitude: 37.86186, longitude: 23.75431, manualId: 'manual:athens:ark-glyfada' },
  { pattern: /asteras beach/i, name: 'Asteras Beach', country: 'Greece', country_code: 'GR', latitude: 37.85828, longitude: 23.7527, manualId: 'manual:athens:asteras-beach' },
  { pattern: /bungalow 7/i, name: 'Bungalow 7', country: 'Greece', country_code: 'GR', latitude: 37.86129, longitude: 23.75404, manualId: 'manual:athens:bungalow-7' },
  { pattern: /ath[eé]n[eé]e/i, name: 'Athénée', country: 'Greece', country_code: 'GR', latitude: 37.97651, longitude: 23.7352, manualId: 'manual:athens:athenee' },
  { pattern: /panathenaic stadium/i, name: 'Panathenaic Stadium', country: 'Greece', country_code: 'GR', latitude: 37.96832, longitude: 23.74168, manualId: 'manual:athens:panathenaic-stadium' },
  { pattern: /mavro provato/i, name: 'Mavro Provato', country: 'Greece', country_code: 'GR', latitude: 37.96886, longitude: 23.74602, manualId: 'manual:athens:mavro-provato' },

  { pattern: /kyoto ramen koji/i, name: 'Kyoto Ramen Koji', country: 'Japan', country_code: 'JP', latitude: 34.98578, longitude: 135.75876, manualId: 'manual:kyoto:ramen-koji' },
  { pattern: /sanjusangendo|sanj[uū]sangen-d[oō]/i, name: 'Sanjusangendo', country: 'Japan', country_code: 'JP', latitude: 34.98789, longitude: 135.77172, manualId: 'manual:kyoto:sanjusangendo' },
  { pattern: /shosei-?en/i, name: 'Shosei-en Garden', country: 'Japan', country_code: 'JP', latitude: 34.99144, longitude: 135.76274, manualId: 'manual:kyoto:shosei-en' },
  { pattern: /musashi sushi|sushi no musashi/i, name: 'Musashi Sushi Kyoto Station Hachijo Entrance', country: 'Japan', country_code: 'JP', latitude: 34.98479, longitude: 135.75913, manualId: 'manual:kyoto:musashi-sushi' },

  { pattern: /museum hill.*artcaffe/i, name: 'Museum Hill Centre Artcaffe', country: 'Kenya', country_code: 'KE', latitude: -1.27444, longitude: 36.81489, manualId: 'manual:nairobi:museum-hill-artcaffe' },
  { pattern: /maasai market.*high court/i, name: 'Maasai Market at The High Court Parking', country: 'Kenya', country_code: 'KE', latitude: -1.28747, longitude: 36.81624, manualId: 'manual:nairobi:maasai-market-high-court' },
  { pattern: /cj'?s koinange/i, name: "CJ's Koinange", country: 'Kenya', country_code: 'KE', latitude: -1.28391, longitude: 36.81935, manualId: 'manual:nairobi:cjs-koinange' },
  { pattern: /thorn tree cafe/i, name: 'Thorn Tree Cafe', country: 'Kenya', country_code: 'KE', latitude: -1.28552, longitude: 36.82002, manualId: 'manual:nairobi:thorn-tree-cafe' },
  { pattern: /village market/i, name: 'Village Market', country: 'Kenya', country_code: 'KE', latitude: -1.22934, longitude: 36.80519, manualId: 'manual:nairobi:village-market' },
  { pattern: /harvest restaurant.*village market/i, name: 'Harvest Restaurant Village Market', country: 'Kenya', country_code: 'KE', latitude: -1.22938, longitude: 36.80541, manualId: 'manual:nairobi:harvest-village-market' },

  { pattern: /philos athens/i, name: 'Philos Athens', country: 'Greece', country_code: 'GR', latitude: 37.97962, longitude: 23.74146, manualId: 'manual:athens:philos' },
  { pattern: /benaki museum/i, name: 'Benaki Museum', country: 'Greece', country_code: 'GR', latitude: 37.97595, longitude: 23.74029, manualId: 'manual:athens:benaki-museum' },
  { pattern: /aleria/i, name: 'Aleria', country: 'Greece', country_code: 'GR', latitude: 37.98169, longitude: 23.71835, manualId: 'manual:athens:aleria' },
  { pattern: /temple of poseidon/i, name: 'Temple of Poseidon', country: 'Greece', country_code: 'GR', latitude: 37.65067, longitude: 24.02448, manualId: 'manual:sounion:temple-of-poseidon' },
  { pattern: /akrogiali/i, name: 'Akrogiali', country: 'Greece', country_code: 'GR', latitude: 37.65128, longitude: 24.02262, manualId: 'manual:sounion:akrogiali' },
  { pattern: /gb roof garden/i, name: 'GB Roof Garden', country: 'Greece', country_code: 'GR', latitude: 37.97556, longitude: 23.73554, manualId: 'manual:athens:gb-roof-garden' },

  { pattern: /russ.*daughters/i, name: 'Russ & Daughters Cafe', country: 'United States', country_code: 'US', latitude: 40.71963, longitude: -73.99095, manualId: 'manual:new-york:russ-daughters-cafe' },
  { pattern: /tenement museum/i, name: 'Tenement Museum', country: 'United States', country_code: 'US', latitude: 40.71882, longitude: -73.99007, manualId: 'manual:new-york:tenement-museum' },
  { pattern: /katz'?s/i, name: "Katz's Delicatessen", country: 'United States', country_code: 'US', latitude: 40.72224, longitude: -73.98743, manualId: 'manual:new-york:katzs' },
  { pattern: /artists.*fleas/i, name: 'Artists & Fleas Williamsburg', country: 'United States', country_code: 'US', latitude: 40.71943, longitude: -73.95967, manualId: 'manual:new-york:artists-fleas' },
  { pattern: /juliette restaurant/i, name: 'Juliette Restaurant', country: 'United States', country_code: 'US', latitude: 40.71785, longitude: -73.95971, manualId: 'manual:new-york:juliette' },
  { pattern: /rule of thirds/i, name: 'Rule of Thirds', country: 'United States', country_code: 'US', latitude: 40.72876, longitude: -73.95727, manualId: 'manual:new-york:rule-of-thirds' },
  { pattern: /chelsea market/i, name: 'Chelsea Market', country: 'United States', country_code: 'US', latitude: 40.74244, longitude: -74.0061, manualId: 'manual:new-york:chelsea-market' },
  { pattern: /poster house/i, name: 'Poster House', country: 'United States', country_code: 'US', latitude: 40.74418, longitude: -73.99954, manualId: 'manual:new-york:poster-house' },
  { pattern: /smalls jazz/i, name: 'Smalls Jazz Club', country: 'United States', country_code: 'US', latitude: 40.73438, longitude: -74.00279, manualId: 'manual:new-york:smalls-jazz' },

  { pattern: /granville island public market/i, name: 'Granville Island Public Market', country: 'Canada', country_code: 'CA', latitude: 49.2721, longitude: -123.13573, manualId: 'manual:vancouver:granville-public-market' },
  { pattern: /a bread affair/i, name: 'A Bread Affair', country: 'Canada', country_code: 'CA', latitude: 49.27212, longitude: -123.13582, manualId: 'manual:vancouver:a-bread-affair' },
  { pattern: /olympic village plaza/i, name: 'Olympic Village Plaza', country: 'Canada', country_code: 'CA', latitude: 49.27082, longitude: -123.10581, manualId: 'manual:vancouver:olympic-village-plaza' },
  { pattern: /tap.*barrel.*olympic/i, name: 'Tap & Barrel Olympic Village', country: 'Canada', country_code: 'CA', latitude: 49.27092, longitude: -123.10639, manualId: 'manual:vancouver:tap-barrel-olympic' },
  { pattern: /david lam park/i, name: 'David Lam Park', country: 'Canada', country_code: 'CA', latitude: 49.27126, longitude: -123.12478, manualId: 'manual:vancouver:david-lam-park' },

  { pattern: /praia da joatinga|joatinga/i, name: 'Praia da Joatinga', country: 'Brazil', country_code: 'BR', latitude: -23.0125, longitude: -43.29195, manualId: 'manual:rio:praia-da-joatinga' },
  { pattern: /bar da laje/i, name: 'Bar da Laje', country: 'Brazil', country_code: 'BR', latitude: -22.94702, longitude: -43.20242, manualId: 'manual:rio:bar-da-laje' },
  { pattern: /boa pra[cç]a/i, name: 'Boa Praça Ipanema', country: 'Brazil', country_code: 'BR', latitude: -22.98451, longitude: -43.20395, manualId: 'manual:rio:boa-praca-ipanema' },

  { pattern: /harpa concert/i, name: 'Harpa Concert Hall', country: 'Iceland', country_code: 'IS', latitude: 64.15027, longitude: -21.93281, manualId: 'manual:reykjavik:harpa' },
  { pattern: /sandholt/i, name: 'Sandholt', country: 'Iceland', country_code: 'IS', latitude: 64.14542, longitude: -21.92888, manualId: 'manual:reykjavik:sandholt' },
  { pattern: /sun voyager/i, name: 'Sun Voyager', country: 'Iceland', country_code: 'IS', latitude: 64.14759, longitude: -21.92215, manualId: 'manual:reykjavik:sun-voyager' },
  { pattern: /sky lagoon/i, name: 'Sky Lagoon', country: 'Iceland', country_code: 'IS', latitude: 64.09953, longitude: -21.94183, manualId: 'manual:reykjavik:sky-lagoon' },
  { pattern: /messinn/i, name: 'Messinn', country: 'Iceland', country_code: 'IS', latitude: 64.14837, longitude: -21.93476, manualId: 'manual:reykjavik:messinn' },
  { pattern: /thingvellir|þingvellir/i, name: 'Þingvellir National Park', country: 'Iceland', country_code: 'IS', latitude: 64.25585, longitude: -21.12955, manualId: 'manual:iceland:thingvellir' },
  { pattern: /fri[dð]heimar/i, name: 'Friðheimar', country: 'Iceland', country_code: 'IS', latitude: 64.1762, longitude: -20.44541, manualId: 'manual:iceland:fridheimar' },
  { pattern: /geysir/i, name: 'Geysir Geothermal Area', country: 'Iceland', country_code: 'IS', latitude: 64.31399, longitude: -20.29952, manualId: 'manual:iceland:geysir' },
  { pattern: /gullfoss/i, name: 'Gullfoss', country: 'Iceland', country_code: 'IS', latitude: 64.32706, longitude: -20.11995, manualId: 'manual:iceland:gullfoss' },
  { pattern: /matarkjallarinn|foodcellar/i, name: 'Matarkjallarinn - Foodcellar', country: 'Iceland', country_code: 'IS', latitude: 64.14621, longitude: -21.94141, manualId: 'manual:reykjavik:matarkjallarinn' },
  { pattern: /brau[dð].*co/i, name: 'Brauð & Co', country: 'Iceland', country_code: 'IS', latitude: 64.1439, longitude: -21.92844, manualId: 'manual:reykjavik:braud-co' },
  { pattern: /grotta lighthouse/i, name: 'Grotta Lighthouse', country: 'Iceland', country_code: 'IS', latitude: 64.16323, longitude: -22.0217, manualId: 'manual:reykjavik:grotta' },
  { pattern: /hallgr[ií]mskirkja/i, name: 'Hallgrímskirkja', country: 'Iceland', country_code: 'IS', latitude: 64.14171, longitude: -21.92662, manualId: 'manual:reykjavik:hallgrimskirkja' },
  { pattern: /apotek kitchen/i, name: 'Apotek Kitchen + Bar', country: 'Iceland', country_code: 'IS', latitude: 64.14717, longitude: -21.93862, manualId: 'manual:reykjavik:apotek' },

  { pattern: /heraklion archaeological museum/i, name: 'Heraklion Archaeological Museum', country: 'Greece', country_code: 'GR', latitude: 35.33901, longitude: 25.13674, manualId: 'manual:crete:heraklion-archaeological' },
  { pattern: /peskesi/i, name: 'Peskesi', country: 'Greece', country_code: 'GR', latitude: 35.34011, longitude: 25.13262, manualId: 'manual:crete:peskesi' },
  { pattern: /knossos palace/i, name: 'Knossos Palace', country: 'Greece', country_code: 'GR', latitude: 35.29862, longitude: 25.1631, manualId: 'manual:crete:knossos' },
  { pattern: /parasties/i, name: 'Parasties Urban Kitchen', country: 'Greece', country_code: 'GR', latitude: 35.34053, longitude: 25.13426, manualId: 'manual:crete:parasties' },
  { pattern: /rethymno beach/i, name: 'Rethymno Beach', country: 'Greece', country_code: 'GR', latitude: 35.36592, longitude: 24.48588, manualId: 'manual:crete:rethymno-beach' },
  { pattern: /^avli(?:,|$)/i, name: 'Avli', country: 'Greece', country_code: 'GR', latitude: 35.36934, longitude: 24.47366, manualId: 'manual:crete:avli-rethymno' },
  { pattern: /fortezza of rethymno/i, name: 'Fortezza of Rethymno', country: 'Greece', country_code: 'GR', latitude: 35.37118, longitude: 24.47133, manualId: 'manual:crete:fortezza-rethymno' },
  { pattern: /to pigadi/i, name: 'To Pigadi', country: 'Greece', country_code: 'GR', latitude: 35.36915, longitude: 24.47461, manualId: 'manual:crete:to-pigadi' },
  { pattern: /chania old venetian harbor|old venetian harbor/i, name: 'Chania Old Venetian Harbor', country: 'Greece', country_code: 'GR', latitude: 35.51883, longitude: 24.01721, manualId: 'manual:crete:chania-venetian-harbor' },
  { pattern: /tamam restaurant/i, name: 'Tamam Restaurant', country: 'Greece', country_code: 'GR', latitude: 35.5168, longitude: 24.01613, manualId: 'manual:crete:tamam' },
  { pattern: /maritime museum of crete/i, name: 'Maritime Museum of Crete', country: 'Greece', country_code: 'GR', latitude: 35.51865, longitude: 24.01512, manualId: 'manual:crete:maritime-museum' },
  { pattern: /thalassino ageri/i, name: 'Thalassino Ageri', country: 'Greece', country_code: 'GR', latitude: 35.51722, longitude: 24.03825, manualId: 'manual:crete:thalassino-ageri' },
  { pattern: /elafonissi beach/i, name: 'Elafonissi Beach', country: 'Greece', country_code: 'GR', latitude: 35.27179, longitude: 23.54086, manualId: 'manual:crete:elafonissi' },
  { pattern: /kosmos fish/i, name: 'Kosmos Fish Tavern', country: 'Greece', country_code: 'GR', latitude: 35.27122, longitude: 23.54215, manualId: 'manual:crete:kosmos-fish' },
  { pattern: /chrisoskalitissa/i, name: 'Chrisoskalitissa Monastery', country: 'Greece', country_code: 'GR', latitude: 35.31191, longitude: 23.53289, manualId: 'manual:crete:chrisoskalitissa' },
  { pattern: /^salis(?:,|$)/i, name: 'Salis', country: 'Greece', country_code: 'GR', latitude: 35.51904, longitude: 24.02141, manualId: 'manual:crete:salis' },
  { pattern: /malia palace/i, name: 'Malia Palace Archaeological Site', country: 'Greece', country_code: 'GR', latitude: 35.2935, longitude: 25.49298, manualId: 'manual:crete:malia-palace' },
  { pattern: /avli in malia/i, name: 'Avli in Malia', country: 'Greece', country_code: 'GR', latitude: 35.28489, longitude: 25.46237, manualId: 'manual:crete:avli-malia' },
  { pattern: /lake voulismeni/i, name: 'Lake Voulismeni', country: 'Greece', country_code: 'GR', latitude: 35.19113, longitude: 25.71326, manualId: 'manual:crete:lake-voulismeni' },
  { pattern: /^piato(?:,|$)/i, name: 'Piato', country: 'Greece', country_code: 'GR', latitude: 35.19064, longitude: 25.71687, manualId: 'manual:crete:piato' },
  { pattern: /ancient city of aptera|aptera/i, name: 'Ancient City of Aptera', country: 'Greece', country_code: 'GR', latitude: 35.46454, longitude: 24.14358, manualId: 'manual:crete:aptera' },
  { pattern: /to stachi/i, name: 'To Stachi', country: 'Greece', country_code: 'GR', latitude: 35.5145, longitude: 24.01941, manualId: 'manual:crete:to-stachi' },
  { pattern: /marathi beach/i, name: 'Marathi Beach', country: 'Greece', country_code: 'GR', latitude: 35.50094, longitude: 24.17412, manualId: 'manual:crete:marathi-beach' },
  { pattern: /patrelantonis/i, name: 'Patrelantonis Fish Taverna', country: 'Greece', country_code: 'GR', latitude: 35.5012, longitude: 24.17362, manualId: 'manual:crete:patrelantonis' },

  { pattern: /national gallery singapore/i, name: 'National Gallery Singapore', country: 'Singapore', country_code: 'SG', latitude: 1.29027, longitude: 103.85196, manualId: 'manual:singapore:national-gallery' },
  { pattern: /lau pa sat/i, name: 'Lau Pa Sat', country: 'Singapore', country_code: 'SG', latitude: 1.28069, longitude: 103.85042, manualId: 'manual:singapore:lau-pa-sat' },
  { pattern: /cloud forest/i, name: 'Cloud Forest', country: 'Singapore', country_code: 'SG', latitude: 1.28474, longitude: 103.86525, manualId: 'manual:singapore:cloud-forest' },
  { pattern: /satay by the bay/i, name: 'Satay by the Bay', country: 'Singapore', country_code: 'SG', latitude: 1.28191, longitude: 103.8687, manualId: 'manual:singapore:satay-by-the-bay' },
  { pattern: /singapore botanic gardens/i, name: 'Singapore Botanic Gardens', country: 'Singapore', country_code: 'SG', latitude: 1.31384, longitude: 103.81591, manualId: 'manual:singapore:botanic-gardens' },
  { pattern: /adam road food centre/i, name: 'Adam Road Food Centre', country: 'Singapore', country_code: 'SG', latitude: 1.32419, longitude: 103.81419, manualId: 'manual:singapore:adam-road-food-centre' },
  { pattern: /national museum of singapore/i, name: 'National Museum of Singapore', country: 'Singapore', country_code: 'SG', latitude: 1.29664, longitude: 103.84847, manualId: 'manual:singapore:national-museum' },
  { pattern: /food opera/i, name: 'Food Opera', country: 'Singapore', country_code: 'SG', latitude: 1.30405, longitude: 103.83185, manualId: 'manual:singapore:food-opera' },
  { pattern: /buddha tooth relic/i, name: 'Buddha Tooth Relic Temple', country: 'Singapore', country_code: 'SG', latitude: 1.28153, longitude: 103.84428, manualId: 'manual:singapore:buddha-tooth-relic' },
  { pattern: /maxwell food centre/i, name: 'Maxwell Food Centre', country: 'Singapore', country_code: 'SG', latitude: 1.28033, longitude: 103.84482, manualId: 'manual:singapore:maxwell-food-centre' },
  { pattern: /jewel changi/i, name: 'Jewel Changi Airport', country: 'Singapore', country_code: 'SG', latitude: 1.36021, longitude: 103.98976, manualId: 'manual:singapore:jewel-changi' },
  { pattern: /violet oon.*jewel/i, name: 'Violet Oon Singapore at Jewel', country: 'Singapore', country_code: 'SG', latitude: 1.36047, longitude: 103.98954, manualId: 'manual:singapore:violet-oon-jewel' },

  { pattern: /armani.*mediterraneo/i, name: 'Armani/Mediterraneo', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.19709, longitude: 55.27418, manualId: 'manual:dubai:armani-mediterraneo' },
  { pattern: /dubai aquarium/i, name: 'Dubai Aquarium & Underwater Zoo', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.19752, longitude: 55.27955, manualId: 'manual:dubai:aquarium' },
  { pattern: /ce la vi dubai|c[eé] la vi/i, name: 'CE LA VI Dubai', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.20194, longitude: 55.27177, manualId: 'manual:dubai:ce-la-vi' },
  { pattern: /al fahidi/i, name: 'Al Fahidi Historical Neighbourhood', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.2637, longitude: 55.30074, manualId: 'manual:dubai:al-fahidi' },
  { pattern: /arabian tea house/i, name: 'Arabian Tea House Restaurant & Cafe', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.26375, longitude: 55.2999, manualId: 'manual:dubai:arabian-tea-house' },
  { pattern: /museum of the future/i, name: 'Museum of the Future', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.21913, longitude: 55.28172, manualId: 'manual:dubai:museum-of-future' },
  { pattern: /^masti(?:,|$)/i, name: 'Masti', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.21697, longitude: 55.25382, manualId: 'manual:dubai:masti' },
  { pattern: /view at the palm/i, name: 'The View at The Palm', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.1132, longitude: 55.13849, manualId: 'manual:dubai:view-at-the-palm' },
  { pattern: /jones the grocer.*palm/i, name: 'Jones the Grocer Palm West Beach', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.1107, longitude: 55.13946, manualId: 'manual:dubai:jones-palm-west' },
  { pattern: /lost chambers/i, name: 'The Lost Chambers Aquarium', country: 'United Arab Emirates', country_code: 'AE', latitude: 25.13046, longitude: 55.11715, manualId: 'manual:dubai:lost-chambers' },

  { pattern: /museo nacional del prado|prado/i, name: 'Museo Nacional del Prado', country: 'Spain', country_code: 'ES', latitude: 40.41378, longitude: -3.69213, manualId: 'manual:madrid:prado' },
  { pattern: /bodega de la ardosa/i, name: 'Bodega de la Ardosa', country: 'Spain', country_code: 'ES', latitude: 40.4235, longitude: -3.70076, manualId: 'manual:madrid:bodega-ardosa' },
  { pattern: /thyssen/i, name: 'Thyssen-Bornemisza National Museum', country: 'Spain', country_code: 'ES', latitude: 40.41603, longitude: -3.69473, manualId: 'manual:madrid:thyssen' },
  { pattern: /casa lucas/i, name: 'Casa Lucas', country: 'Spain', country_code: 'ES', latitude: 40.41412, longitude: -3.70814, manualId: 'manual:madrid:casa-lucas' },
  { pattern: /atocha/i, name: 'Madrid-Puerta de Atocha-Almudena Grandes', country: 'Spain', country_code: 'ES', latitude: 40.40659, longitude: -3.68919, manualId: 'manual:madrid:atocha' },
  { pattern: /sevilla-santa justa|seville santa justa/i, name: 'Sevilla-Santa Justa', country: 'Spain', country_code: 'ES', latitude: 37.39206, longitude: -5.97407, manualId: 'manual:seville:santa-justa' },
  { pattern: /real alc[aá]zar/i, name: 'Real Alcázar de Sevilla', country: 'Spain', country_code: 'ES', latitude: 37.38309, longitude: -5.99023, manualId: 'manual:seville:real-alcazar' },
  { pattern: /el rinconcillo/i, name: 'El Rinconcillo', country: 'Spain', country_code: 'ES', latitude: 37.39326, longitude: -5.98802, manualId: 'manual:seville:el-rinconcillo' },
  { pattern: /seville cathedral/i, name: 'Seville Cathedral', country: 'Spain', country_code: 'ES', latitude: 37.38583, longitude: -5.99311, manualId: 'manual:seville:cathedral' },
  { pattern: /casa morales/i, name: 'Casa Morales', country: 'Spain', country_code: 'ES', latitude: 37.38683, longitude: -5.99573, manualId: 'manual:seville:casa-morales' },
  { pattern: /casa de la memoria/i, name: 'Casa de la Memoria', country: 'Spain', country_code: 'ES', latitude: 37.39177, longitude: -5.99265, manualId: 'manual:seville:casa-memoria' },
  { pattern: /mercado de triana/i, name: 'Mercado de Triana', country: 'Spain', country_code: 'ES', latitude: 37.38594, longitude: -6.00102, manualId: 'manual:seville:mercado-triana' },
  { pattern: /las golondrinas/i, name: 'Las Golondrinas', country: 'Spain', country_code: 'ES', latitude: 37.38434, longitude: -6.00304, manualId: 'manual:seville:las-golondrinas' },
  { pattern: /centro cer[aá]mica triana/i, name: 'Centro Cerámica Triana', country: 'Spain', country_code: 'ES', latitude: 37.38564, longitude: -6.00167, manualId: 'manual:seville:ceramica-triana' },
  { pattern: /puente de isabel ii/i, name: 'Puente de Isabel II', country: 'Spain', country_code: 'ES', latitude: 37.38651, longitude: -6.00099, manualId: 'manual:seville:puente-isabel' },
  { pattern: /casa de pilatos/i, name: 'Casa de Pilatos', country: 'Spain', country_code: 'ES', latitude: 37.38972, longitude: -5.9877, manualId: 'manual:seville:casa-de-pilatos' },
  { pattern: /bar alfalfa/i, name: 'Bar Alfalfa', country: 'Spain', country_code: 'ES', latitude: 37.38943, longitude: -5.99031, manualId: 'manual:seville:bar-alfalfa' },
  { pattern: /metropol parasol|setas de sevilla/i, name: 'Metropol Parasol', country: 'Spain', country_code: 'ES', latitude: 37.39322, longitude: -5.99168, manualId: 'manual:seville:metropol-parasol' },

  { pattern: /victrola coffee/i, name: 'Victrola Coffee Roasters', country: 'United States', country_code: 'US', latitude: 47.6146, longitude: -122.31923, manualId: 'manual:seattle:victrola' },
  { pattern: /olympic sculpture park/i, name: 'Olympic Sculpture Park', country: 'United States', country_code: 'US', latitude: 47.61658, longitude: -122.35538, manualId: 'manual:seattle:olympic-sculpture-park' },
  { pattern: /toulouse petit/i, name: 'Toulouse Petit Kitchen & Lounge', country: 'United States', country_code: 'US', latitude: 47.62473, longitude: -122.35695, manualId: 'manual:seattle:toulouse-petit' },
  { pattern: /mopop|museum of pop culture/i, name: 'MoPOP', country: 'United States', country_code: 'US', latitude: 47.62148, longitude: -122.34812, manualId: 'manual:seattle:mopop' },
  { pattern: /jazz alley/i, name: "Dimitriou's Jazz Alley", country: 'United States', country_code: 'US', latitude: 47.61465, longitude: -122.33969, manualId: 'manual:seattle:jazz-alley' },
]
