export type RegionalPlaceOverride = {
  pattern: RegExp
  name: string
  country: string
  country_code: string
  latitude: number
  longitude: number
  manualId: string
}

export const REGIONAL_PLACE_OVERRIDES: RegionalPlaceOverride[] = [
  { pattern: /hagia sophia/i, name: 'Hagia Sophia Grand Mosque', country: 'Turkey', country_code: 'TR', latitude: 41.00858, longitude: 28.98017, manualId: 'manual:istanbul:hagia-sophia' },
  { pattern: /\bmatbah\b/i, name: 'Matbah Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.00769, longitude: 28.97973, manualId: 'manual:istanbul:matbah' },
  { pattern: /basilica cistern/i, name: 'Basilica Cistern', country: 'Turkey', country_code: 'TR', latitude: 41.00838, longitude: 28.97788, manualId: 'manual:istanbul:basilica-cistern' },
  { pattern: /grand bazaar/i, name: 'Grand Bazaar', country: 'Turkey', country_code: 'TR', latitude: 41.01068, longitude: 28.96807, manualId: 'manual:istanbul:grand-bazaar' },
  { pattern: /seven hills/i, name: 'Seven Hills Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.00597, longitude: 28.98072, manualId: 'manual:istanbul:seven-hills' },
  { pattern: /mısır çarşısı|misir carsisi|spice bazaar/i, name: 'Mısır Çarşısı', country: 'Turkey', country_code: 'TR', latitude: 41.01646, longitude: 28.97055, manualId: 'manual:istanbul:spice-bazaar' },
  { pattern: /pandeli/i, name: 'Pandeli Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.01644, longitude: 28.97046, manualId: 'manual:istanbul:pandeli' },
  { pattern: /eminönü ferry|eminonu ferry|şehir hatları eminönü|sehir hatlari eminonu/i, name: 'Eminönü Ferry Terminal', country: 'Turkey', country_code: 'TR', latitude: 41.01728, longitude: 28.97507, manualId: 'manual:istanbul:eminonu-ferry' },
  { pattern: /kadıköy çarşı|kadikoy carsisi|kadıköy market|kadikoy market/i, name: 'Kadıköy Çarşı', country: 'Turkey', country_code: 'TR', latitude: 40.99057, longitude: 29.02647, manualId: 'manual:istanbul:kadikoy-carsi' },
  { pattern: /hamdi/i, name: 'Hamdi Restaurant', country: 'Turkey', country_code: 'TR', latitude: 41.01641, longitude: 28.97097, manualId: 'manual:istanbul:hamdi' },
  { pattern: /topkapı palace|topkapi palace/i, name: 'Topkapı Palace Museum', country: 'Turkey', country_code: 'TR', latitude: 41.01152, longitude: 28.98338, manualId: 'manual:istanbul:topkapi-palace' },
  { pattern: /karaköy lokantası|karakoy lokantasi/i, name: 'Karaköy Lokantası', country: 'Turkey', country_code: 'TR', latitude: 41.02432, longitude: 28.97705, manualId: 'manual:istanbul:karakoy-lokantasi' },
  { pattern: /galata tower/i, name: 'Galata Tower', country: 'Turkey', country_code: 'TR', latitude: 41.02557, longitude: 28.97413, manualId: 'manual:istanbul:galata-tower' },
  { pattern: /istanbul modern|i̇stanbul modern/i, name: 'Istanbul Modern', country: 'Turkey', country_code: 'TR', latitude: 41.02589, longitude: 28.98237, manualId: 'manual:istanbul:modern' },
  { pattern: /\bmikla\b/i, name: 'Mikla', country: 'Turkey', country_code: 'TR', latitude: 41.02814, longitude: 28.97493, manualId: 'manual:istanbul:mikla' },
  { pattern: /balat antik/i, name: 'Balat Antik Cafe', country: 'Turkey', country_code: 'TR', latitude: 41.02924, longitude: 28.94993, manualId: 'manual:istanbul:balat-antik' },
  { pattern: /fener rum|orthodox patriarchate/i, name: 'Fener Greek Orthodox Patriarchate', country: 'Turkey', country_code: 'TR', latitude: 41.02978, longitude: 28.95151, manualId: 'manual:istanbul:fener-patriarchate' },
  { pattern: /bulgarian st\.?\s*stephen|st\.?\s*stephen church|sveti stefan/i, name: 'Bulgarian St. Stephen Church', country: 'Turkey', country_code: 'TR', latitude: 41.0296, longitude: 28.94952, manualId: 'manual:istanbul:bulgarian-st-stephen' },
  { pattern: /chora church|kariye mosque/i, name: 'Chora Church', country: 'Turkey', country_code: 'TR', latitude: 41.03193, longitude: 28.93938, manualId: 'manual:istanbul:chora-church' },
  { pattern: /meze by lemon tree/i, name: 'Meze By Lemon Tree', country: 'Turkey', country_code: 'TR', latitude: 41.03141, longitude: 28.97301, manualId: 'manual:istanbul:meze-lemon-tree' },

  { pattern: /gyeongbokgung/i, name: 'Gyeongbokgung Palace', country: 'South Korea', country_code: 'KR', latitude: 37.57962, longitude: 126.97704, manualId: 'manual:seoul:gyeongbokgung' },
  { pattern: /tosokchon/i, name: 'Tosokchon Samgyetang', country: 'South Korea', country_code: 'KR', latitude: 37.57741, longitude: 126.97191, manualId: 'manual:seoul:tosokchon' },
  { pattern: /bukchon hanok/i, name: 'Bukchon Hanok Village', country: 'South Korea', country_code: 'KR', latitude: 37.5826, longitude: 126.984, manualId: 'manual:seoul:bukchon-hanok' },
  { pattern: /cheongsudang/i, name: 'Cheongsudang', country: 'South Korea', country_code: 'KR', latitude: 37.57438, longitude: 126.98966, manualId: 'manual:seoul:cheongsudang' },
  { pattern: /changhwadang/i, name: 'Changhwadang Ikseon', country: 'South Korea', country_code: 'KR', latitude: 37.57403, longitude: 126.98992, manualId: 'manual:seoul:changhwadang-ikseon' },
  { pattern: /myeong-?dong cathedral/i, name: 'Myeongdong Cathedral', country: 'South Korea', country_code: 'KR', latitude: 37.56337, longitude: 126.98734, manualId: 'manual:seoul:myeongdong-cathedral' },
  { pattern: /myeongdong kyoja/i, name: 'Myeongdong Kyoja Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56255, longitude: 126.98506, manualId: 'manual:seoul:myeongdong-kyoja' },
  { pattern: /lotte department store.*main/i, name: 'Lotte Department Store Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56482, longitude: 126.98164, manualId: 'manual:seoul:lotte-main-store' },
  { pattern: /wangbijip/i, name: 'Wangbijip Myeongdong Main Store', country: 'South Korea', country_code: 'KR', latitude: 37.56298, longitude: 126.9858, manualId: 'manual:seoul:wangbijip-myeongdong' },
  { pattern: /n seoul tower|namsan tower/i, name: 'N Seoul Tower', country: 'South Korea', country_code: 'KR', latitude: 37.55117, longitude: 126.98823, manualId: 'manual:seoul:n-seoul-tower' },
  { pattern: /starfield coex|coex mall/i, name: 'Starfield COEX Mall', country: 'South Korea', country_code: 'KR', latitude: 37.51168, longitude: 127.05915, manualId: 'manual:seoul:starfield-coex' },
  { pattern: /woo lae oak.*coex|wooraeok.*coex/i, name: 'Woo Lae Oak COEX', country: 'South Korea', country_code: 'KR', latitude: 37.51282, longitude: 127.05912, manualId: 'manual:seoul:woo-lae-oak-coex' },
  { pattern: /bongeunsa/i, name: 'Bongeunsa Temple', country: 'South Korea', country_code: 'KR', latitude: 37.515, longitude: 127.0574, manualId: 'manual:seoul:bongeunsa' },
  { pattern: /spa lei/i, name: 'Spa Lei', country: 'South Korea', country_code: 'KR', latitude: 37.51654, longitude: 127.01935, manualId: 'manual:seoul:spa-lei' },
  { pattern: /yang good/i, name: 'Yang Good Gangnam Main Branch', country: 'South Korea', country_code: 'KR', latitude: 37.5139, longitude: 127.0287, manualId: 'manual:seoul:yang-good-gangnam' },
  { pattern: /gyeongui line forest/i, name: 'Gyeongui Line Forest Park', country: 'South Korea', country_code: 'KR', latitude: 37.5596, longitude: 126.9237, manualId: 'manual:seoul:gyeongui-line-forest' },
  { pattern: /cafe layered.*yeonnam|layered yeonnam/i, name: 'Cafe Layered Yeonnam', country: 'South Korea', country_code: 'KR', latitude: 37.5623, longitude: 126.9236, manualId: 'manual:seoul:cafe-layered-yeonnam' },
  { pattern: /hongdae shopping/i, name: 'Hongdae Shopping Street', country: 'South Korea', country_code: 'KR', latitude: 37.553, longitude: 126.9226, manualId: 'manual:seoul:hongdae-shopping-street' },
  { pattern: /myth jokbal/i, name: 'Myth Jokbal Hongdae', country: 'South Korea', country_code: 'KR', latitude: 37.5508, longitude: 126.9219, manualId: 'manual:seoul:myth-jokbal-hongdae' },
  { pattern: /sangsangmadang/i, name: 'KT&G Sangsangmadang Hongdae', country: 'South Korea', country_code: 'KR', latitude: 37.5507, longitude: 126.921, manualId: 'manual:seoul:sangsangmadang-hongdae' },
  { pattern: /^seoul forest(?:,|$)|seoul forest park/i, name: 'Seoul Forest', country: 'South Korea', country_code: 'KR', latitude: 37.54439, longitude: 127.03744, manualId: 'manual:seoul:seoul-forest' },
  { pattern: /grandmother'?s recipe/i, name: "Grandmother's Recipe", country: 'South Korea', country_code: 'KR', latitude: 37.5471, longitude: 127.0429, manualId: 'manual:seoul:grandmothers-recipe' },
  { pattern: /musinsa standard.*seongsu/i, name: 'Musinsa Standard Seongsu', country: 'South Korea', country_code: 'KR', latitude: 37.5446, longitude: 127.054, manualId: 'manual:seoul:musinsa-standard-seongsu' },
  { pattern: /center coffee.*seoul forest/i, name: 'Center Coffee Seoul Forest', country: 'South Korea', country_code: 'KR', latitude: 37.5467, longitude: 127.0436, manualId: 'manual:seoul:center-coffee-seoul-forest' },
  { pattern: /banpo hangang/i, name: 'Banpo Hangang Park', country: 'South Korea', country_code: 'KR', latitude: 37.5126, longitude: 126.9961, manualId: 'manual:seoul:banpo-hangang-park' },

  { pattern: /wat pho/i, name: 'Wat Pho', country: 'Thailand', country_code: 'TH', latitude: 13.74651, longitude: 100.49276, manualId: 'manual:bangkok:wat-pho' },
  { pattern: /the sixth|6th/i, name: 'The Sixth 6th', country: 'Thailand', country_code: 'TH', latitude: 13.74496, longitude: 100.49264, manualId: 'manual:bangkok:the-sixth' },
  { pattern: /grand palace/i, name: 'Grand Palace', country: 'Thailand', country_code: 'TH', latitude: 13.75003, longitude: 100.49135, manualId: 'manual:bangkok:grand-palace' },
  { pattern: /wat arun/i, name: 'Wat Arun', country: 'Thailand', country_code: 'TH', latitude: 13.74372, longitude: 100.48894, manualId: 'manual:bangkok:wat-arun' },
  { pattern: /supanniga/i, name: 'Supanniga Eating Room Tha Tien', country: 'Thailand', country_code: 'TH', latitude: 13.74434, longitude: 100.49284, manualId: 'manual:bangkok:supanniga-tha-tien' },
  { pattern: /jim thompson/i, name: 'Jim Thompson House Museum', country: 'Thailand', country_code: 'TH', latitude: 13.74912, longitude: 100.52839, manualId: 'manual:bangkok:jim-thompson-house' },
  { pattern: /baan khun mae|ban khun mae/i, name: 'Baan Khun Mae', country: 'Thailand', country_code: 'TH', latitude: 13.74652, longitude: 100.53232, manualId: 'manual:bangkok:baan-khun-mae' },
  { pattern: /bangkok art and culture|bacc/i, name: 'Bangkok Art and Culture Centre', country: 'Thailand', country_code: 'TH', latitude: 13.74666, longitude: 100.53005, manualId: 'manual:bangkok:bacc' },
  { pattern: /jodd fairs/i, name: 'Jodd Fairs Night Market', country: 'Thailand', country_code: 'TH', latitude: 13.75881, longitude: 100.56551, manualId: 'manual:bangkok:jodd-fairs' },
  { pattern: /chatuchak/i, name: 'Chatuchak Weekend Market', country: 'Thailand', country_code: 'TH', latitude: 13.79982, longitude: 100.55053, manualId: 'manual:bangkok:chatuchak' },
  { pattern: /or tor kor/i, name: 'Or Tor Kor Market', country: 'Thailand', country_code: 'TH', latitude: 13.79788, longitude: 100.54879, manualId: 'manual:bangkok:or-tor-kor' },
  { pattern: /lumphini|lumpini/i, name: 'Lumphini Park', country: 'Thailand', country_code: 'TH', latitude: 13.73072, longitude: 100.54178, manualId: 'manual:bangkok:lumphini-park' },
  { pattern: /tep bar/i, name: 'Tep Bar', country: 'Thailand', country_code: 'TH', latitude: 13.73841, longitude: 100.51308, manualId: 'manual:bangkok:tep-bar' },
  { pattern: /wat traimit/i, name: 'Wat Traimit', country: 'Thailand', country_code: 'TH', latitude: 13.7378, longitude: 100.5137, manualId: 'manual:bangkok:wat-traimit' },
  { pattern: /nai ek/i, name: 'Nai Ek Roll Noodle', country: 'Thailand', country_code: 'TH', latitude: 13.74048, longitude: 100.51042, manualId: 'manual:bangkok:nai-ek' },
  { pattern: /yaowarat/i, name: 'Yaowarat Road', country: 'Thailand', country_code: 'TH', latitude: 13.74004, longitude: 100.51004, manualId: 'manual:bangkok:yaowarat-road' },
  { pattern: /pak khlong talat|flower market/i, name: 'Pak Khlong Talat', country: 'Thailand', country_code: 'TH', latitude: 13.7419, longitude: 100.49643, manualId: 'manual:bangkok:pak-khlong-talat' },
  { pattern: /ruen mallika/i, name: 'Ruen Mallika Royal Thai Cuisine', country: 'Thailand', country_code: 'TH', latitude: 13.7229, longitude: 100.53372, manualId: 'manual:bangkok:ruen-mallika' },

  { pattern: /le jardin secret/i, name: 'Le Jardin Secret', country: 'Morocco', country_code: 'MA', latitude: 31.63014, longitude: -7.9892, manualId: 'manual:marrakech:le-jardin-secret' },
  { pattern: /^nomad|nomad,/i, name: 'Nomad', country: 'Morocco', country_code: 'MA', latitude: 31.62831, longitude: -7.98757, manualId: 'manual:marrakech:nomad' },
  { pattern: /maison de la photographie/i, name: 'Maison de la Photographie', country: 'Morocco', country_code: 'MA', latitude: 31.63171, longitude: -7.98538, manualId: 'manual:marrakech:maison-photographie' },
  { pattern: /dar cherifa/i, name: 'Dar Cherifa', country: 'Morocco', country_code: 'MA', latitude: 31.63055, longitude: -7.9893, manualId: 'manual:marrakech:dar-cherifa' },
  { pattern: /souk semmarine/i, name: 'Souk Semmarine', country: 'Morocco', country_code: 'MA', latitude: 31.62776, longitude: -7.98813, manualId: 'manual:marrakech:souk-semmarine' },
  { pattern: /jardin majorelle/i, name: 'Jardin Majorelle', country: 'Morocco', country_code: 'MA', latitude: 31.64172, longitude: -8.00327, manualId: 'manual:marrakech:jardin-majorelle' },
  { pattern: /yves saint laurent|ysl/i, name: 'Musée Yves Saint Laurent Marrakech', country: 'Morocco', country_code: 'MA', latitude: 31.6429, longitude: -8.00331, manualId: 'manual:marrakech:ysl-museum' },
  { pattern: /plus61/i, name: 'Plus61', country: 'Morocco', country_code: 'MA', latitude: 31.62901, longitude: -8.01575, manualId: 'manual:marrakech:plus61' },
  { pattern: /cyber park|arsat moulay/i, name: 'Cyber Park Arsat Moulay Abdeslam', country: 'Morocco', country_code: 'MA', latitude: 31.62679, longitude: -8.00074, manualId: 'manual:marrakech:cyber-park' },
  { pattern: /^le jardin$|le jardin,/i, name: 'Le Jardin', country: 'Morocco', country_code: 'MA', latitude: 31.6306, longitude: -7.98695, manualId: 'manual:marrakech:le-jardin' },
  { pattern: /bahia palace/i, name: 'Bahia Palace', country: 'Morocco', country_code: 'MA', latitude: 31.62181, longitude: -7.98204, manualId: 'manual:marrakech:bahia-palace' },
  { pattern: /el badi|badi palace/i, name: 'El Badi Palace', country: 'Morocco', country_code: 'MA', latitude: 31.61872, longitude: -7.98672, manualId: 'manual:marrakech:el-badi-palace' },
  { pattern: /dar si said/i, name: 'Dar Si Said Museum', country: 'Morocco', country_code: 'MA', latitude: 31.62332, longitude: -7.98415, manualId: 'manual:marrakech:dar-si-said' },
  { pattern: /la famille/i, name: 'La Famille', country: 'Morocco', country_code: 'MA', latitude: 31.62347, longitude: -7.98578, manualId: 'manual:marrakech:la-famille' },
  { pattern: /kabana/i, name: 'Kabana', country: 'Morocco', country_code: 'MA', latitude: 31.6271, longitude: -7.99046, manualId: 'manual:marrakech:kabana' },

  { pattern: /table mountain aerial cableway/i, name: 'Table Mountain Aerial Cableway', country: 'South Africa', country_code: 'ZA', latitude: -33.9486, longitude: 18.4035, manualId: 'manual:cape-town:table-mountain-cableway' },
  { pattern: /bo-?kaap museum/i, name: 'Bo-Kaap Museum', country: 'South Africa', country_code: 'ZA', latitude: -33.9219, longitude: 18.4156, manualId: 'manual:cape-town:bo-kaap-museum' },
  { pattern: /kloof street house/i, name: 'Kloof Street House', country: 'South Africa', country_code: 'ZA', latitude: -33.9295, longitude: 18.4105, manualId: 'manual:cape-town:kloof-street-house' },
  { pattern: /signal hill/i, name: 'Signal Hill', country: 'South Africa', country_code: 'ZA', latitude: -33.9177, longitude: 18.4031, manualId: 'manual:cape-town:signal-hill' },
  { pattern: /athletic club.*social/i, name: 'The Athletic Club & Social', country: 'South Africa', country_code: 'ZA', latitude: -33.923, longitude: 18.4173, manualId: 'manual:cape-town:athletic-club-social' },
  { pattern: /lion'?s head/i, name: "Lion's Head Trailhead", country: 'South Africa', country_code: 'ZA', latitude: -33.9368, longitude: 18.3926, manualId: 'manual:cape-town:lions-head-trailhead' },
  { pattern: /jarryds/i, name: 'JARRYDS Brunch & Bistro', country: 'South Africa', country_code: 'ZA', latitude: -33.9184, longitude: 18.3852, manualId: 'manual:cape-town:jarryds' },
  { pattern: /clifton 4th|fourth beach/i, name: 'Clifton 4th Beach', country: 'South Africa', country_code: 'ZA', latitude: -33.9408, longitude: 18.3757, manualId: 'manual:cape-town:clifton-4th-beach' },
  { pattern: /camps bay beach/i, name: 'Camps Bay Beach', country: 'South Africa', country_code: 'ZA', latitude: -33.9513, longitude: 18.384, manualId: 'manual:cape-town:camps-bay-beach' },
  { pattern: /codfather/i, name: 'Codfather Seafood & Sushi', country: 'South Africa', country_code: 'ZA', latitude: -33.9548, longitude: 18.3814, manualId: 'manual:cape-town:codfather' },
  { pattern: /groot constantia/i, name: 'Groot Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0314, longitude: 18.4198, manualId: 'manual:cape-town:groot-constantia' },
  { pattern: /chefs warehouse.*beau constantia/i, name: 'Chefs Warehouse at Beau Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0206, longitude: 18.4027, manualId: 'manual:cape-town:chefs-warehouse-beau-constantia' },
  { pattern: /^beau constantia(?:,|$)/i, name: 'Beau Constantia', country: 'South Africa', country_code: 'ZA', latitude: -34.0204, longitude: 18.4031, manualId: 'manual:cape-town:beau-constantia' },
  { pattern: /constantia glen/i, name: 'Constantia Glen', country: 'South Africa', country_code: 'ZA', latitude: -34.0089, longitude: 18.4053, manualId: 'manual:cape-town:constantia-glen' },
  { pattern: /buitenverwachting/i, name: 'Buitenverwachting', country: 'South Africa', country_code: 'ZA', latitude: -34.0316, longitude: 18.4318, manualId: 'manual:cape-town:buitenverwachting' },
  { pattern: /franschhoek wine tram/i, name: 'Franschhoek Wine Tram', country: 'South Africa', country_code: 'ZA', latitude: -33.9107, longitude: 19.1191, manualId: 'manual:franschhoek:wine-tram' },
  { pattern: /chamonix wine farm/i, name: 'Chamonix Wine Farm', country: 'South Africa', country_code: 'ZA', latitude: -33.8942, longitude: 19.1133, manualId: 'manual:franschhoek:chamonix-wine-farm' },
  { pattern: /la petite colombe/i, name: 'La Petite Colombe', country: 'South Africa', country_code: 'ZA', latitude: -33.8948, longitude: 19.1091, manualId: 'manual:franschhoek:la-petite-colombe' },
  { pattern: /^gold restaurant|gold street/i, name: 'GOLD Restaurant', country: 'South Africa', country_code: 'ZA', latitude: -33.9141, longitude: 18.4175, manualId: 'manual:cape-town:gold-restaurant' },
  { pattern: /seaforth restaurant/i, name: 'Seaforth Restaurant', country: 'South Africa', country_code: 'ZA', latitude: -34.1955, longitude: 18.4507, manualId: 'manual:simonstown:seaforth-restaurant' },
  { pattern: /boulders beach|penguin colony/i, name: 'Boulders Beach Penguin Colony', country: 'South Africa', country_code: 'ZA', latitude: -34.197, longitude: 18.4519, manualId: 'manual:simonstown:boulders-beach' },
  { pattern: /cape of good hope/i, name: 'Cape of Good Hope', country: 'South Africa', country_code: 'ZA', latitude: -34.3568, longitude: 18.474, manualId: 'manual:cape-point:cape-of-good-hope' },
  { pattern: /cape point/i, name: 'Cape Point', country: 'South Africa', country_code: 'ZA', latitude: -34.356, longitude: 18.4964, manualId: 'manual:cape-point:cape-point' },
  { pattern: /harbour house.*kalk bay/i, name: 'Harbour House Kalk Bay', country: 'South Africa', country_code: 'ZA', latitude: -34.1274, longitude: 18.449, manualId: 'manual:kalk-bay:harbour-house' },
  { pattern: /kirstenbosch/i, name: 'Kirstenbosch National Botanical Garden', country: 'South Africa', country_code: 'ZA', latitude: -33.9881, longitude: 18.4326, manualId: 'manual:cape-town:kirstenbosch' },
  { pattern: /oranjezicht city farm/i, name: 'Oranjezicht City Farm Market', country: 'South Africa', country_code: 'ZA', latitude: -33.9046, longitude: 18.4148, manualId: 'manual:cape-town:oranjezicht-market' },
  { pattern: /v\s*&\s*a waterfront|v&a waterfront|waterfront/i, name: 'V&A Waterfront', country: 'South Africa', country_code: 'ZA', latitude: -33.9068, longitude: 18.4206, manualId: 'manual:cape-town:va-waterfront' },
  { pattern: /zeitz mocaa/i, name: 'Zeitz MOCAA', country: 'South Africa', country_code: 'ZA', latitude: -33.9085, longitude: 18.4228, manualId: 'manual:cape-town:zeitz-mocaa' },
  { pattern: /old biscuit mill/i, name: 'The Old Biscuit Mill', country: 'South Africa', country_code: 'ZA', latitude: -33.9273, longitude: 18.4575, manualId: 'manual:cape-town:old-biscuit-mill' },
  { pattern: /lawns.*roundhouse/i, name: 'The Lawns at the Roundhouse', country: 'South Africa', country_code: 'ZA', latitude: -33.9419, longitude: 18.3783, manualId: 'manual:cape-town:lawns-roundhouse' },
  { pattern: /pot luck club/i, name: 'The Pot Luck Club', country: 'South Africa', country_code: 'ZA', latitude: -33.9275, longitude: 18.4574, manualId: 'manual:cape-town:pot-luck-club' },

  { pattern: /sydney opera house/i, name: 'Sydney Opera House', country: 'Australia', country_code: 'AU', latitude: -33.85678, longitude: 151.2153, manualId: 'manual:sydney:opera-house' },
  { pattern: /city extra/i, name: 'City Extra 24 Hour Restaurant', country: 'Australia', country_code: 'AU', latitude: -33.86162, longitude: 151.21197, manualId: 'manual:sydney:city-extra' },
  { pattern: /rocks discovery/i, name: 'The Rocks Discovery Museum', country: 'Australia', country_code: 'AU', latitude: -33.85902, longitude: 151.20875, manualId: 'manual:sydney:rocks-discovery-museum' },
  { pattern: /museum of contemporary art/i, name: 'Museum of Contemporary Art Australia', country: 'Australia', country_code: 'AU', latitude: -33.85992, longitude: 151.20903, manualId: 'manual:sydney:mca' },
  { pattern: /mures circular quay|circular quay/i, name: 'Mures Circular Quay', country: 'Australia', country_code: 'AU', latitude: -33.86165, longitude: 151.21215, manualId: 'manual:sydney:mures-circular-quay' },
  { pattern: /bondi icebergs/i, name: 'Bondi Icebergs Club', country: 'Australia', country_code: 'AU', latitude: -33.89502, longitude: 151.27432, manualId: 'manual:sydney:bondi-icebergs' },
  { pattern: /bills bondi/i, name: 'Bills Bondi', country: 'Australia', country_code: 'AU', latitude: -33.88979, longitude: 151.27011, manualId: 'manual:sydney:bills-bondi' },
  { pattern: /bondi to bronte/i, name: 'Bondi to Bronte Coastal Walk', country: 'Australia', country_code: 'AU', latitude: -33.89954, longitude: 151.2727, manualId: 'manual:sydney:bondi-bronte-walk' },
  { pattern: /bronte baths/i, name: 'Bronte Baths', country: 'Australia', country_code: 'AU', latitude: -33.90453, longitude: 151.26867, manualId: 'manual:sydney:bronte-baths' },
  { pattern: /fish at the rocks/i, name: 'Fish At The Rocks', country: 'Australia', country_code: 'AU', latitude: -33.85867, longitude: 151.2082, manualId: 'manual:sydney:fish-at-the-rocks' },
  { pattern: /manly ferry|manly wharf/i, name: 'Manly Wharf', country: 'Australia', country_code: 'AU', latitude: -33.8002, longitude: 151.28448, manualId: 'manual:sydney:manly-wharf' },
  { pattern: /manly pavilion/i, name: 'Manly Pavilion', country: 'Australia', country_code: 'AU', latitude: -33.79962, longitude: 151.28462, manualId: 'manual:sydney:manly-pavilion' },
  { pattern: /shelly beach/i, name: 'Shelly Beach', country: 'Australia', country_code: 'AU', latitude: -33.80086, longitude: 151.29865, manualId: 'manual:sydney:shelly-beach' },
  { pattern: /north head/i, name: 'North Head Lookout', country: 'Australia', country_code: 'AU', latitude: -33.81362, longitude: 151.30031, manualId: 'manual:sydney:north-head-lookout' },
  { pattern: /sake restaurant.*rocks|sake.*rocks/i, name: 'Sake Restaurant & Bar The Rocks', country: 'Australia', country_code: 'AU', latitude: -33.85882, longitude: 151.20878, manualId: 'manual:sydney:sake-the-rocks' },
  { pattern: /royal botanic garden/i, name: 'Royal Botanic Garden Sydney', country: 'Australia', country_code: 'AU', latitude: -33.86419, longitude: 151.21657, manualId: 'manual:sydney:royal-botanic-garden' },
  { pattern: /paddington reservoir/i, name: 'Paddington Reservoir Gardens', country: 'Australia', country_code: 'AU', latitude: -33.8844, longitude: 151.22932, manualId: 'manual:sydney:paddington-reservoir' },
  { pattern: /art gallery of new south wales/i, name: 'Art Gallery of New South Wales', country: 'Australia', country_code: 'AU', latitude: -33.8688, longitude: 151.2173, manualId: 'manual:sydney:art-gallery-nsw' },
  { pattern: /grounds of alexandria/i, name: 'The Grounds of Alexandria', country: 'Australia', country_code: 'AU', latitude: -33.91078, longitude: 151.19487, manualId: 'manual:sydney:grounds-alexandria' },
  { pattern: /saint peter/i, name: 'Saint Peter', country: 'Australia', country_code: 'AU', latitude: -33.88984, longitude: 151.23049, manualId: 'manual:sydney:saint-peter' },
]
